/* GENERATED by packages/tokens/scripts/generate-radix.ts from @radix-ui/colors; do not edit. */

export const RADIX_VERSION = '3.0.0';

export const RADIX_SCALES = ['slate', 'indigo', 'teal', 'crimson', 'orange', 'purple', 'cyan', 'amber'] as const;
export type RadixScaleName = (typeof RADIX_SCALES)[number];

export type Scale12 = readonly [
  string, string, string, string, string, string,
  string, string, string, string, string, string,
];

export const RADIX: Record<RadixScaleName, { light: Scale12; dark: Scale12 }> = {
  slate: {
    light: ['#fcfcfd', '#f9f9fb', '#f0f0f3', '#e8e8ec', '#e0e1e6', '#d9d9e0', '#cdced6', '#b9bbc6', '#8b8d98', '#80838d', '#60646c', '#1c2024'],
    dark: ['#111113', '#18191b', '#212225', '#272a2d', '#2e3135', '#363a3f', '#43484e', '#5a6169', '#696e77', '#777b84', '#b0b4ba', '#edeef0'],
  },
  indigo: {
    light: ['#fdfdfe', '#f7f9ff', '#edf2fe', '#e1e9ff', '#d2deff', '#c1d0ff', '#abbdf9', '#8da4ef', '#3e63dd', '#3358d4', '#3a5bc7', '#1f2d5c'],
    dark: ['#11131f', '#141726', '#182449', '#1d2e62', '#253974', '#304384', '#3a4f97', '#435db1', '#3e63dd', '#5472e4', '#9eb1ff', '#d6e1ff'],
  },
  teal: {
    light: ['#fafefd', '#f3fbf9', '#e0f8f3', '#ccf3ea', '#b8eae0', '#a1ded2', '#83cdc1', '#53b9ab', '#12a594', '#0d9b8a', '#008573', '#0d3d38'],
    dark: ['#0d1514', '#111c1b', '#0d2d2a', '#023b37', '#084843', '#145750', '#1c6961', '#207e73', '#12a594', '#0eb39e', '#0bd8b6', '#adf0dd'],
  },
  crimson: {
    light: ['#fffcfd', '#fef7f9', '#ffe9f0', '#fedce7', '#facedd', '#f3bed1', '#eaacc3', '#e093b2', '#e93d82', '#df3478', '#cb1d63', '#621639'],
    dark: ['#191114', '#201318', '#381525', '#4d122f', '#5c1839', '#6d2545', '#873356', '#b0436e', '#e93d82', '#ee518a', '#ff92ad', '#fdd3e8'],
  },
  orange: {
    light: ['#fefcfb', '#fff7ed', '#ffefd6', '#ffdfb5', '#ffd19a', '#ffc182', '#f5ae73', '#ec9455', '#f76b15', '#ef5f00', '#cc4e00', '#582d1d'],
    dark: ['#17120e', '#1e160f', '#331e0b', '#462100', '#562800', '#66350c', '#7e451d', '#a35829', '#f76b15', '#ff801f', '#ffa057', '#ffe0c2'],
  },
  purple: {
    light: ['#fefcfe', '#fbf7fe', '#f7edfe', '#f2e2fc', '#ead5f9', '#e0c4f4', '#d1afec', '#be93e4', '#8e4ec6', '#8347b9', '#8145b5', '#402060'],
    dark: ['#18111b', '#1e1523', '#301c3b', '#3d224e', '#48295c', '#54346b', '#664282', '#8457aa', '#8e4ec6', '#9a5cd0', '#d19dff', '#ecd9fa'],
  },
  cyan: {
    light: ['#fafdfe', '#f2fafb', '#def7f9', '#caf1f6', '#b5e9f0', '#9ddde7', '#7dcedc', '#3db9cf', '#00a2c7', '#0797b9', '#107d98', '#0d3c48'],
    dark: ['#0b161a', '#101b20', '#082c36', '#003848', '#004558', '#045468', '#12677e', '#11809c', '#00a2c7', '#23afd0', '#4ccce6', '#b6ecf7'],
  },
  amber: {
    light: ['#fefdfb', '#fefbe9', '#fff7c2', '#ffee9c', '#fbe577', '#f3d673', '#e9c162', '#e2a336', '#ffc53d', '#ffba18', '#ab6400', '#4f3422'],
    dark: ['#16120c', '#1d180f', '#302008', '#3f2700', '#4d3000', '#5c3d05', '#714f19', '#8f6424', '#ffc53d', '#ffd60a', '#ffca16', '#ffe7b3'],
  },
};
