/**
 * The settings key TABLE (RT-47/RT-50): rt's rows, verbatim. A later task
 * grows this table with the rest of the suite (deck/board/gitq/mattstack/
 * claude keys) — the machinery in registry-machinery.ts that reads and
 * validates against this table does not change when rows are added.
 */

import type { SettingDef, SettingScope } from "./registry-machinery.ts";

const ALL_SCOPES: SettingScope[] = ["user", "team", "machine"];

export const REGISTRY: SettingDef[] = [
  // --- migrated:true (wave 1) ---------------------------------------------
  {
    key: "rt.roles",
    type: "object",
    scopes: ALL_SCOPES,
    merge: "deep",
    repoScoped: true,
    migrated: true,
    pathGuardFields: ["hook"],
    description: "Per-repo dev-role definitions: port pools, env passthrough, and the dev-server hook command.",
  },
  {
    key: "rt.intercepts",
    type: "array",
    scopes: ALL_SCOPES,
    merge: "replace",
    repoScoped: true,
    migrated: true,
    description: "Per-repo endpoint intercept rules consumed by rt intercept install.",
  },
  {
    key: "rt.worktrees",
    type: "object",
    scopes: ALL_SCOPES,
    default: { onDeck: 0 },
    merge: "deep",
    repoScoped: true,
    migrated: true,
    description: "Per-repo worktree pool config (onDeck size, ready steps, name pool); root/branchFormat/ready computed-or-empty in the reader.",
  },
  {
    key: "rt.repoIdentityOverrides",
    type: "object",
    scopes: ["machine"],
    merge: "replace",
    migrated: true,
    description: "Map of observed remote URL to pinned repo identity, for forks/multi-remote repos on this machine.",
  },
  {
    key: "rt.repoRoots",
    type: "array",
    scopes: ["machine"],
    default: [],
    merge: "replace",
    migrated: true,
    description:
      'Directories rt scans for git repos (rt cd, run-outside-a-repo pickers). Entries may start with "~/" or use "${home}". One level deep, plus worktree-pool parent folders one level deeper.',
  },

  // --- migrated:false (wave 1 legacy-file keys) ---------------------------
  {
    key: "rt.llm",
    type: "object",
    scopes: ALL_SCOPES,
    merge: "deep",
    migrated: false,
    legacyFile: "llm.json",
    description: "LLM provider and model selection for rt's AI-assisted commands.",
  },
  {
    key: "rt.cron",
    type: "object",
    scopes: ALL_SCOPES,
    merge: "deep",
    migrated: false,
    legacyFile: "cron.jsonc",
    description: "Scheduled rt job definitions and their cron expressions.",
  },
  {
    key: "rt.repoTracking",
    type: "object",
    scopes: ALL_SCOPES,
    merge: "deep",
    migrated: false,
    legacyFile: "repo-tracking.json",
    description: "Which repos rt tracks for background sync and status polling.",
  },
  {
    key: "rt.notifications",
    type: "object",
    scopes: ALL_SCOPES,
    merge: "deep",
    migrated: false,
    legacyFile: "notifications.json",
    siblingCommand: "rt settings notifications",
    description: "Desktop notification preferences (which events notify, sound on/off).",
  },
  {
    key: "rt.sync",
    type: "object",
    scopes: ALL_SCOPES,
    merge: "deep",
    repoScoped: true,
    migrated: false,
    legacyFile: "repos/<repo>/sync.json",
    description: "Branch sync behavior: fast-forward rules and stale-branch handling.",
  },
  {
    key: "rt.branchNaming",
    type: "object",
    scopes: ALL_SCOPES,
    merge: "deep",
    repoScoped: true,
    migrated: false,
    legacyFile: "repos/<repo>/branch-naming.json",
    description: "Templates rt uses to derive branch names from ticket identifiers.",
  },
  {
    key: "rt.variations",
    type: "object",
    scopes: ALL_SCOPES,
    merge: "deep",
    repoScoped: true,
    migrated: false,
    legacyFile: "repos/<repo>/variations.json",
    description: "Named parameter sets rt run can pick between for a command.",
  },
  {
    key: "rt.presets",
    type: "object",
    scopes: ALL_SCOPES,
    merge: "deep",
    repoScoped: true,
    migrated: false,
    legacyFile: "repos/<repo>/presets/<name>.json",
    description: "Saved argument presets for frequently repeated rt commands.",
  },
  {
    key: "rt.dopplerTemplate",
    type: "object",
    scopes: ALL_SCOPES,
    merge: "deep",
    repoScoped: true,
    migrated: false,
    legacyFile: "repos/<repo>/doppler-template.yaml",
    description: "Template used to generate a repo's Doppler secrets config.",
  },
  {
    key: "rt.workspacePrefs",
    type: "object",
    scopes: ALL_SCOPES,
    merge: "deep",
    migrated: false,
    legacyFile: "workspace-prefs.json",
    description: "Per-machine editor/terminal preferences applied when opening a worktree.",
  },
  {
    key: "rt.runaway",
    type: "object",
    scopes: ALL_SCOPES,
    merge: "deep",
    migrated: false,
    legacyFile: "runaway-config.json",
    siblingCommand: "rt settings runaway",
    description: "Thresholds for the runaway-process guard that kills stuck dev servers.",
  },
  {
    key: "rt.hooks",
    type: "object",
    scopes: ALL_SCOPES,
    merge: "deep",
    repoScoped: true,
    migrated: false,
    legacyFile: "repos/<repo>/hooks.json",
    description: "User-defined lifecycle hooks rt runs around commands (pre/post command scripts).",
  },
];
