import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';

import { tokyoRamps } from '../../tokyo/src/ramps.ts';
import { srgbLuminance } from '../src/color-math.ts';
import { RADIX } from '../src/radix.ts';

const source = readFileSync(
  join(import.meta.dirname, '..', '..', 'tokyo', 'src', 'ramps.ts'),
  'utf8'
);
const DAY_PICK = [1, 3, 4, 5, 6, 7, 9, 10, 11, 12];
const NIGHT_PICK = [12, 11, 10, 9, 8, 7, 6, 5, 4, 3];

describe('generated ramps', () => {
  it('ramps.ts is a generated file', () => {
    expect(
      source.startsWith(
        '/* GENERATED by packages/tokens/scripts/generate-ramps.ts; do not edit. */'
      )
    ).toBe(true);
  });

  it.each(Object.entries(tokyoRamps))('%s has ten stops', (_name, stops) => {
    expect(stops).toHaveLength(10);
    for (const s of stops) expect(s).toMatch(/^#[0-9a-f]{6}$/);
  });

  it.each([
    ['accent', 'indigo'],
    ['ok', 'teal'],
    ['bad', 'crimson'],
    ['warn', 'orange'],
    ['purple', 'purple'],
    ['cyan', 'cyan'],
  ] as const)(
    '%s tuples are the documented pick from the %s scale',
    (hue, scale) => {
      expect([...tokyoRamps[`${hue}Day`]]).toEqual(
        DAY_PICK.map(s => RADIX[scale].light[s - 1])
      );
      expect([...tokyoRamps[`${hue}Night`]]).toEqual(
        NIGHT_PICK.map(s => RADIX[scale].dark[s - 1])
      );
    }
  );

  it('the day tuples darken from stop 0 to the primary stop 6', () => {
    // Radix amber (gold) is a bright-accent scale, not a lightness ramp: its
    // step 9 (the day tuple's stop 6) is brighter than step 7 (stop 5), the
    // opposite of every other hue vendored here. Excluded rather than forced.
    for (const [name, stops] of Object.entries(tokyoRamps)) {
      if (!name.endsWith('Day') || name === 'goldDay') continue;
      const lums = stops.slice(0, 7).map(srgbLuminance);
      for (let i = 1; i < lums.length; i++)
        expect(lums[i], `${name} stop ${i}`).toBeLessThan(lums[i - 1]!);
    }
  });

  it('gray and dark tuples come from slate', () => {
    expect(tokyoRamps.grayDay[4]).toBe(RADIX.slate.light[6]);
    expect(tokyoRamps.grayDay[6]).toBe(RADIX.slate.light[10]);
    expect(tokyoRamps.darkNight[4]).toBe(RADIX.slate.dark[7]);
    expect(tokyoRamps.darkNight[5]).toBe(RADIX.slate.dark[3]);
    expect(tokyoRamps.darkNight[6]).toBe(RADIX.slate.dark[2]);
    expect(tokyoRamps.darkNight[2]).toBe(RADIX.slate.dark[10]);
    expect(tokyoRamps.darkNight[7]).toBe(RADIX.slate.dark[1]);
  });
});
