import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { CSS_TEXT, TOKENS, type ColorScheme } from '../src/values.ts';

const REPO_ROOT = join(import.meta.dirname, '..', '..');
const TUI_KIT_TOKENS_TS = join(
  REPO_ROOT,
  'tui-kit',
  'src',
  'generated',
  'tokens.ts'
);

const HEADER = '/* GENERATED by packages/tokens; do not edit. */\n';

/**
 * `CSS_TEXT[path] ?? value` is the byte-identity contract with theme.ts's
 * historical literals (see values.ts): a path with no override prints its
 * canonical value verbatim, `light.text.fg` prints the shipped 3-digit spelling.
 */
function pick(path: string, value: string): string {
  return CSS_TEXT[path] ?? value;
}

/**
 * Maps a TOKENS color scheme onto tui-kit's `tuiTheme.tokens.colors` /
 * `TUI_DARK_COLORS` shape. tui-kit has one canonical shade per hue (`"500"`)
 * where TOKENS has a bare hex, and collapses `text` to the two leaves
 * (`fg`, `muted`) it consumes -- `mutedText`/`accentText`/`wash` are not part
 * of this phase's consumption scope.
 */
function buildTuiKitColors(scheme: 'light' | 'dark') {
  const t: ColorScheme = TOKENS[scheme];
  const at = (leaf: string, value: string) => pick(`${scheme}.${leaf}`, value);
  return {
    blue: { '500': at('hue.accent', t.hue.accent) },
    green: { '500': at('hue.ok', t.hue.ok) },
    red: { '500': at('hue.bad', t.hue.bad) },
    amber: { '500': at('hue.warn', t.hue.warn) },
    purple: { '500': at('hue.purple', t.hue.purple) },
    cyan: { '500': at('hue.cyan', t.hue.cyan) },
    gray: {
      fg: at('text.fg', t.text.fg),
      muted: at('text.muted', t.text.muted),
    },
    surface: {
      bg: at('surface.bg', t.surface.bg),
      panel: at('surface.panel', t.surface.panel),
      card: at('surface.card', t.surface.card),
      chrome: at('surface.chrome', t.surface.chrome),
    },
    line: {
      border: at('line.border', t.line.border),
      soft: at('line.soft', t.line.soft),
      grid: at('line.grid', t.line.grid),
    },
    dot: {
      ok: at('dot.ok', t.dot.ok),
      warn: at('dot.warn', t.dot.warn),
      bad: at('dot.bad', t.dot.bad),
    },
  };
}

function buildTuiKitFontFamily() {
  return {
    mono: pick('font.mono', TOKENS.font.mono),
    sans: pick('font.sans', TOKENS.font.sans),
  };
}

function renderConst(name: string, value: unknown): string {
  return `export const ${name} = ${JSON.stringify(value, null, 2)} as const;\n`;
}

function generateTuiKitTokens(): string {
  const lightColors = buildTuiKitColors('light');
  const darkColors = buildTuiKitColors('dark');
  const fontFamily = buildTuiKitFontFamily();
  const lineHeightBase = pick('font.lineHeight', TOKENS.font.lineHeight);

  return (
    HEADER +
    '\n' +
    renderConst('GENERATED_LIGHT_COLORS', lightColors) +
    '\n' +
    renderConst('GENERATED_DARK_COLORS', darkColors) +
    '\n' +
    renderConst('GENERATED_FONT_FAMILY', fontFamily) +
    '\n' +
    `export const GENERATED_LINE_HEIGHT_BASE = ${JSON.stringify(lineHeightBase)} as const;\n`
  );
}

function main() {
  writeFileSync(TUI_KIT_TOKENS_TS, generateTuiKitTokens());
}

main();
