import { copyFileSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { CSS_TEXT, TOKENS, type ColorScheme } from '../src/values.ts';

const REPO_ROOT = join(import.meta.dirname, '..', '..');
const TUI_KIT_TOKENS_TS = join(
  REPO_ROOT,
  'tui-kit',
  'src',
  'generated',
  'tokens.ts'
);
const TOKYO_THEME_CSS = join(REPO_ROOT, 'tokyo', 'src', 'tokyo-theme.css');

const FONT_FILENAME = 'jetbrains-mono.woff2';
const FONT_SOURCE = join(import.meta.dirname, '..', 'assets', FONT_FILENAME);
const FONT_TARGETS = [
  join(REPO_ROOT, 'tokyo', 'src', 'fonts', FONT_FILENAME),
  join(REPO_ROOT, 'tui-kit', 'assets', 'fonts', FONT_FILENAME),
];

const HEADER = '/* GENERATED by packages/tokens; do not edit. */\n';

/**
 * `CSS_TEXT[path] ?? value` is the byte-identity contract with theme.ts's
 * historical literals (see values.ts): a path with no override prints its
 * canonical value verbatim, `light.text.fg` prints the shipped 3-digit spelling.
 */
function pick(path: string, value: string): string {
  return CSS_TEXT[path] ?? value;
}

/**
 * Maps a TOKENS color scheme onto tui-kit's `tuiTheme.tokens.colors` /
 * `TUI_DARK_COLORS` shape. tui-kit has one canonical shade per hue (`"500"`)
 * where TOKENS has a bare hex, and collapses `text` to the two leaves
 * (`fg`, `muted`) it consumes -- `mutedText`/`accentText`/`wash` are not part
 * of this phase's consumption scope.
 */
function buildTuiKitColors(scheme: 'light' | 'dark') {
  const t: ColorScheme = TOKENS[scheme];
  const at = (leaf: string, value: string) => pick(`${scheme}.${leaf}`, value);
  return {
    blue: { '500': at('hue.accent', t.hue.accent) },
    green: { '500': at('hue.ok', t.hue.ok) },
    red: { '500': at('hue.bad', t.hue.bad) },
    amber: { '500': at('hue.warn', t.hue.warn) },
    purple: { '500': at('hue.purple', t.hue.purple) },
    cyan: { '500': at('hue.cyan', t.hue.cyan) },
    gray: {
      fg: at('text.fg', t.text.fg),
      muted: at('text.muted', t.text.muted),
    },
    surface: {
      bg: at('surface.bg', t.surface.bg),
      panel: at('surface.panel', t.surface.panel),
      card: at('surface.card', t.surface.card),
      chrome: at('surface.chrome', t.surface.chrome),
    },
    line: {
      border: at('line.border', t.line.border),
      soft: at('line.soft', t.line.soft),
      grid: at('line.grid', t.line.grid),
    },
    dot: {
      ok: at('dot.ok', t.dot.ok),
      warn: at('dot.warn', t.dot.warn),
      bad: at('dot.bad', t.dot.bad),
    },
  };
}

function buildTuiKitFontFamily() {
  return {
    mono: pick('font.mono', TOKENS.font.mono),
    sans: pick('font.sans', TOKENS.font.sans),
  };
}

function renderConst(name: string, value: unknown): string {
  return `export const ${name} = ${JSON.stringify(value, null, 2)} as const;\n`;
}

function generateTuiKitTokens(): string {
  const lightColors = buildTuiKitColors('light');
  const darkColors = buildTuiKitColors('dark');
  const fontFamily = buildTuiKitFontFamily();
  const lineHeightBase = pick('font.lineHeight', TOKENS.font.lineHeight);

  return (
    HEADER +
    '\n' +
    renderConst('GENERATED_LIGHT_COLORS', lightColors) +
    '\n' +
    renderConst('GENERATED_DARK_COLORS', darkColors) +
    '\n' +
    renderConst('GENERATED_FONT_FAMILY', fontFamily) +
    '\n' +
    `export const GENERATED_LINE_HEIGHT_BASE = ${JSON.stringify(lineHeightBase)} as const;\n`
  );
}

/**
 * Comment text inside the two `--tk-*` scheme blocks. Not derived from
 * TOKENS -- these are prose, kept verbatim in the emitter template per the
 * marker contract (see the BEGIN/END markers in tokyo-theme.css).
 */
const TOKYO_LIGHT_TOP_COMMENT = `  /* Light surface ramp, Supabase model: a near-white canvas, a subtle grey chrome
     frame, and true-white content. Contrast rides text and element borders on the
     light ground, not surface-to-surface fill. --tk-chrome is the frame grey (app
     rail/nav); it is deliberately kept OUT of the bg/panel/card elevation ladder so
     that ladder stays ordered (bg < panel < card) AND near-white -- panel is the
     raised content surface, not the chrome. Without the split, panel had to be both
     and the ladder inverted (--bg ended up lighter than --panel). The chrome
     retarget below maps rail/nav onto --tk-chrome and PageShell header/sidebar +
     content onto card. */`;
const TOKYO_LIGHT_MUTED_TEXT_COMMENT = `  /* AA-compliant muted for TEXT (>=4.5:1 on bg 1-3). The raw muted token above
     stays tui-kit's exact hex for dots/borders; only the muted TEXT roles read
     the value below, which the scheme-vars contract lets an app remap. */`;
const TOKYO_LIGHT_ACCENT_TEXT_COMMENT = `  /* AA-compliant accent for LINK TEXT (>=4.5:1 on bg 1-3). The raw accent
     token above stays tui-kit's exact hex for fills and badges; only anchor
     text reads the darker value below. Same split as the muted pair. */`;
const TOKYO_DARK_TOP_COMMENT = `  /* Dark never inverted (bg < panel < card already), so --tk-chrome equals the
     panel rung: the rail/nav frame reads as a step up from the near-black page. */`;
const TOKYO_DARK_MUTED_TEXT_COMMENT =
  '  /* AA-compliant muted text for the dark scheme (>=4.5:1 on bg 1-3). */';
const TOKYO_DARK_ACCENT_TEXT_COMMENT = `  /* Accent for link text in dark (>=4.5:1 on bg 1-3); the accent already
     clears AA there, so this equals it. */`;

function buildTokyoDeclarations(scheme: 'light' | 'dark') {
  const t: ColorScheme = TOKENS[scheme];
  const at = (leaf: string, value: string) => pick(`${scheme}.${leaf}`, value);
  return {
    chrome: at('surface.chrome', t.surface.chrome),
    bg: at('surface.bg', t.surface.bg),
    panel: at('surface.panel', t.surface.panel),
    card: at('surface.card', t.surface.card),
    border: at('line.border', t.line.border),
    borderSoft: at('line.soft', t.line.soft),
    fg: at('text.fg', t.text.fg),
    muted: at('text.muted', t.text.muted),
    mutedText: at('text.mutedText', t.text.mutedText),
    accent: at('hue.accent', t.hue.accent),
    accentText: at('text.accentText', t.text.accentText),
    green: at('hue.ok', t.hue.ok),
    red: at('hue.bad', t.hue.bad),
    amber: at('hue.warn', t.hue.warn),
    purple: at('hue.purple', t.hue.purple),
    cyan: at('hue.cyan', t.hue.cyan),
    gridLine: at('line.grid', t.line.grid),
    dotOk: at('dot.ok', t.dot.ok),
    dotWarn: at('dot.warn', t.dot.warn),
    dotBad: at('dot.bad', t.dot.bad),
    wash: at('wash', t.wash),
  };
}

function renderTokyoSchemeBlock(scheme: 'light' | 'dark'): string {
  const d = buildTokyoDeclarations(scheme);
  const topComment =
    scheme === 'light' ? TOKYO_LIGHT_TOP_COMMENT : TOKYO_DARK_TOP_COMMENT;
  const mutedTextComment =
    scheme === 'light'
      ? TOKYO_LIGHT_MUTED_TEXT_COMMENT
      : TOKYO_DARK_MUTED_TEXT_COMMENT;
  const accentTextComment =
    scheme === 'light'
      ? TOKYO_LIGHT_ACCENT_TEXT_COMMENT
      : TOKYO_DARK_ACCENT_TEXT_COMMENT;
  return [
    topComment,
    `  --tk-chrome: ${d.chrome};`,
    `  --tk-bg: ${d.bg};`,
    `  --tk-panel: ${d.panel};`,
    `  --tk-card: ${d.card};`,
    `  --tk-border: ${d.border};`,
    `  --tk-border-soft: ${d.borderSoft};`,
    `  --tk-fg: ${d.fg};`,
    `  --tk-muted: ${d.muted};`,
    mutedTextComment,
    `  --tk-muted-text: ${d.mutedText};`,
    `  --tk-accent: ${d.accent};`,
    accentTextComment,
    `  --tk-accent-text: ${d.accentText};`,
    `  --tk-green: ${d.green};`,
    `  --tk-red: ${d.red};`,
    `  --tk-amber: ${d.amber};`,
    `  --tk-purple: ${d.purple};`,
    `  --tk-cyan: ${d.cyan};`,
    `  --tk-grid-line: ${d.gridLine};`,
    `  --tk-dot-ok: ${d.dotOk};`,
    `  --tk-dot-warn: ${d.dotWarn};`,
    `  --tk-dot-bad: ${d.dotBad};`,
    '',
    `  --tk-wash: ${d.wash};`,
  ].join('\n');
}

/**
 * Splices `body` between one BEGIN/END marker pair, replacing whatever
 * currently sits there. The markers themselves are left untouched --
 * everything else in tokyo-theme.css is hand-authored and never moves.
 *
 * `endMarker` text is shared by every scheme block, so a lone `indexOf`
 * for it would happily match a later block's END if this block's own END
 * were missing -- that read would splice `body` across the boundary into
 * the next block instead of failing. The next-BEGIN check below closes
 * that: any BEGIN marker between this one and the matched END means the
 * END wasn't this block's, so it throws instead of splicing silently.
 */
export function spliceGenerated(
  css: string,
  beginMarker: string,
  body: string
): string {
  const endMarker = '/* END GENERATED */';
  const beginIdx = css.indexOf(beginMarker);
  if (beginIdx === -1) {
    throw new Error(`tokyo-theme.css: marker not found: ${beginMarker}`);
  }
  if (css.indexOf(beginMarker, beginIdx + 1) !== -1) {
    throw new Error(`tokyo-theme.css: duplicate marker: ${beginMarker}`);
  }
  const afterBegin = beginIdx + beginMarker.length;
  const endIdx = css.indexOf(endMarker, afterBegin);
  if (endIdx === -1) {
    throw new Error(`tokyo-theme.css: no END GENERATED after ${beginMarker}`);
  }
  const nextBeginPattern = /\/\* BEGIN GENERATED:.*?\*\//g;
  nextBeginPattern.lastIndex = afterBegin;
  const nextBegin = nextBeginPattern.exec(css);
  if (nextBegin !== null && nextBegin.index < endIdx) {
    throw new Error(
      `tokyo-theme.css: no END GENERATED before the next BEGIN marker after ${beginMarker}`
    );
  }
  return css.slice(0, afterBegin) + '\n' + body + '\n  ' + css.slice(endIdx);
}

function generateTokyoThemeCss(): string {
  let css = readFileSync(TOKYO_THEME_CSS, 'utf8');
  css = spliceGenerated(
    css,
    '/* BEGIN GENERATED: tokyo tokens light */',
    renderTokyoSchemeBlock('light')
  );
  css = spliceGenerated(
    css,
    '/* BEGIN GENERATED: tokyo tokens dark */',
    renderTokyoSchemeBlock('dark')
  );
  return css;
}

function copyFont(): void {
  for (const target of FONT_TARGETS) {
    copyFileSync(FONT_SOURCE, target);
  }
}

function main() {
  writeFileSync(TUI_KIT_TOKENS_TS, generateTuiKitTokens());
  writeFileSync(TOKYO_THEME_CSS, generateTokyoThemeCss());
  copyFont();
}

// Guarded so the test suite can import spliceGenerated without triggering a
// write-to-disk as a side effect of the import.
if (import.meta.main) {
  main();
}
