import { copyFileSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import {
  FONT_SMOOTHING_BEGIN_MARKER,
  FONT_SMOOTHING_END_MARKER,
  renderFontSmoothing,
} from '../src/fragments.ts';
import { mantinePins } from '../src/mantine-pins.ts';
import {
  CSS_TEXT,
  HUES,
  TOKENS,
  type ColorScheme,
  type HueName,
} from '../src/values.ts';

const PACKAGES_ROOT = join(import.meta.dirname, '..', '..');
const TUI_KIT_TOKENS_TS = join(
  PACKAGES_ROOT,
  'tui-kit',
  'src',
  'generated',
  'tokens.ts'
);
const TOKYO_THEME_CSS = join(PACKAGES_ROOT, 'tokyo', 'src', 'tokyo-theme.css');

const FONT_FILENAME = 'jetbrains-mono.woff2';
const FONT_SOURCE = join(import.meta.dirname, '..', 'assets', FONT_FILENAME);
const FONT_TARGETS = [
  join(PACKAGES_ROOT, 'tokyo', 'src', 'fonts', FONT_FILENAME),
  join(PACKAGES_ROOT, 'tui-kit', 'assets', 'fonts', FONT_FILENAME),
];

const HEADER = '/* GENERATED by packages/tokens; do not edit. */\n';

/**
 * `CSS_TEXT[path] ?? value` is the byte-identity contract with theme.ts's
 * historical literals (see values.ts): a path with no override prints its
 * canonical value verbatim, `light.text.fg` prints the shipped 3-digit spelling.
 */
function pick(path: string, value: string): string {
  return CSS_TEXT[path] ?? value;
}

/**
 * Maps a TOKENS color scheme onto tui-kit's `tuiTheme.tokens.colors` /
 * `TUI_DARK_COLORS` shape. Each hue family carries its fill (`"500"`), hover,
 * text and small-text steps; the three neutral ramps land as `ground`, `ink`
 * and `rule` keyed by 1-based index; `text` collapses to the nine leaves tui-kit
 * consumes -- `wash` is a percentage, not a color, and stays out of this map.
 */
function buildTuiKitColors(scheme: 'light' | 'dark') {
  const t: ColorScheme = TOKENS[scheme];
  const at = (leaf: string, value: string) => pick(`${scheme}.${leaf}`, value);
  const family = (hue: HueName) => ({
    '500': at(`hue.${hue}`, t.hue[hue]),
    hover: at(`hueHover.${hue}`, t.hueHover[hue]),
    onFill: at(`hueOnFill.${hue}`, t.hueOnFill[hue]),
    text: at(`hueText.${hue}`, t.hueText[hue]),
    textSmall: at(`hueTextSmall.${hue}`, t.hueTextSmall[hue]),
    textVivid: at(`hueTextVivid.${hue}`, t.hueTextVivid[hue]),
  });
  const ramp = (leaf: string, values: readonly string[]) =>
    Object.fromEntries(
      values.map((v, i) => [String(i + 1), at(`${leaf}.${i}`, v)])
    );
  return {
    blue: family('accent'),
    green: family('ok'),
    red: family('bad'),
    amber: family('warn'),
    purple: family('purple'),
    cyan: family('cyan'),
    gold: family('gold'),
    ground: ramp('surfaceRamp', t.surfaceRamp),
    ink: ramp('textRamp', t.textRamp),
    rule: ramp('lineRamp', t.lineRamp),
    gray: {
      fg: at('text.fg', t.text.fg),
      muted: at('text.muted', t.text.muted),
      mutedText: at('text.mutedText', t.text.mutedText),
      accentText: at('text.accentText', t.text.accentText),
      okText: at('text.okText', t.text.okText),
      warnText: at('text.warnText', t.text.warnText),
      badgeText: at('text.badgeText', t.text.badgeText),
      redText: at('text.redText', t.text.redText),
      mutedOnCard: at('text.mutedOnCard', t.text.mutedOnCard),
    },
    surface: {
      bg: at('surface.bg', t.surface.bg),
      panel: at('surface.panel', t.surface.panel),
      card: at('surface.card', t.surface.card),
      chrome: at('surface.chrome', t.surface.chrome),
      inset: at('surface.inset', t.surface.inset),
      overlay: at('surface.overlay', t.surface.overlay),
      raised: at('surface.raised', t.surface.raised),
    },
    line: {
      border: at('line.border', t.line.border),
      soft: at('line.soft', t.line.soft),
      grid: at('line.grid', t.line.grid),
      control: at('line.control', t.line.control),
      edgeOnCard: at('line.edgeOnCard', t.line.edgeOnCard),
      controlEdgeOnCard: at('line.controlEdgeOnCard', t.line.controlEdgeOnCard),
      softOnCard: at('line.softOnCard', t.line.softOnCard),
    },
    dot: {
      ok: at('hue.ok', t.hue.ok),
      warn: at('hue.warn', t.hue.warn),
      bad: at('hue.bad', t.hue.bad),
    },
  };
}

function buildTuiKitFontFamily() {
  return {
    mono: pick('font.mono', TOKENS.font.mono),
    sans: pick('font.sans', TOKENS.font.sans),
  };
}

function renderConst(name: string, value: unknown): string {
  return `export const ${name} = ${JSON.stringify(value, null, 2)} as const;\n`;
}

function generateTuiKitTokens(): string {
  const lightColors = buildTuiKitColors('light');
  const darkColors = buildTuiKitColors('dark');
  const fontFamily = buildTuiKitFontFamily();
  const lineHeightBase = pick('font.lineHeight', TOKENS.font.lineHeight);

  return (
    HEADER +
    '\n' +
    renderConst('GENERATED_LIGHT_COLORS', lightColors) +
    '\n' +
    renderConst('GENERATED_DARK_COLORS', darkColors) +
    '\n' +
    renderConst('GENERATED_FONT_FAMILY', fontFamily) +
    '\n' +
    `export const GENERATED_LINE_HEIGHT_BASE = ${JSON.stringify(lineHeightBase)} as const;\n`
  );
}

/**
 * Comment text inside the two `--tk-*` scheme blocks. Not derived from
 * TOKENS -- these are prose, kept verbatim in the emitter template per the
 * marker contract (see the BEGIN/END markers in tokyo-theme.css).
 */
const TOKYO_LIGHT_TOP_COMMENT = `  /* Light surfaces: white cards on Radix slate 2 to 4 (packages/tokens/src/radix.ts); contrast rides text and borders, not surface-to-surface fill. */`;
const TOKYO_LIGHT_MUTED_TEXT_COMMENT = `  /* AA-compliant muted for TEXT (>=4.5:1 on bg 1-3). The raw muted token above
     stays tui-kit's exact hex for dots/borders; only the muted TEXT roles read
     the value below, which the scheme-vars contract lets an app remap. */`;
const TOKYO_LIGHT_ACCENT_TEXT_COMMENT = `  /* AA-compliant accent for LINK TEXT (>=4.5:1 on bg 1-3). The raw accent
     token above stays tui-kit's exact hex for fills and badges; only anchor
     text reads the darker value below. Same split as the muted pair. */`;
const TOKYO_LIGHT_RED_TEXT_COMMENT =
  "  /* AA-compliant red for TEXT (>=4.5:1 on bg 1-3); the raw red token above stays tui-kit's exact hex for fills and error surfaces. Same split as the muted/accent pair. */";
const TOKYO_DARK_TOP_COMMENT = `  /* Dark surfaces: Radix slate 1 to 4, page darkest, cards on step 3, step 4 reserved for raised grounds. */`;
const TOKYO_DARK_MUTED_TEXT_COMMENT =
  '  /* AA-compliant muted text for the dark scheme (>=4.5:1 on bg 1-3). */';
const TOKYO_DARK_ACCENT_TEXT_COMMENT = `  /* Accent for link text in dark (>=4.5:1 on bg 1-3); the accent already
     clears AA there, so this equals it. */`;
const TOKYO_DARK_RED_TEXT_COMMENT =
  '  /* Red text for the dark scheme; the raw red already clears AA there, so this equals it. */';

function buildTokyoDeclarations(scheme: 'light' | 'dark') {
  const t: ColorScheme = TOKENS[scheme];
  const at = (leaf: string, value: string) => pick(`${scheme}.${leaf}`, value);
  return {
    chrome: at('surface.chrome', t.surface.chrome),
    bg: at('surface.bg', t.surface.bg),
    panel: at('surface.panel', t.surface.panel),
    card: at('surface.card', t.surface.card),
    border: at('line.border', t.line.border),
    borderSoft: at('line.soft', t.line.soft),
    borderOnCard: at('line.edgeOnCard', t.line.edgeOnCard),
    controlEdge: at('line.controlEdgeOnCard', t.line.controlEdgeOnCard),
    fg: at('text.fg', t.text.fg),
    muted: at('text.muted', t.text.muted),
    mutedText: at('text.mutedText', t.text.mutedText),
    mutedOnCard: at('text.mutedOnCard', t.text.mutedOnCard),
    inset: at('surface.inset', t.surface.inset),
    overlay: at('surface.overlay', t.surface.overlay),
    softOnCard: at('line.softOnCard', t.line.softOnCard),
    accent: at('hue.accent', t.hue.accent),
    accentText: at('text.accentText', t.text.accentText),
    okText: at('text.okText', t.text.okText),
    badgeText: at('text.badgeText', t.text.badgeText),
    green: at('hue.ok', t.hue.ok),
    red: at('hue.bad', t.hue.bad),
    redText: at('text.redText', t.text.redText),
    amber: at('hue.warn', t.hue.warn),
    amberText: at('text.warnText', t.text.warnText),
    purple: at('hue.purple', t.hue.purple),
    cyan: at('hue.cyan', t.hue.cyan),
    gridLine: at('line.grid', t.line.grid),
    dotOk: at('hue.ok', t.hue.ok),
    dotWarn: at('hue.warn', t.hue.warn),
    dotBad: at('hue.bad', t.hue.bad),
    wash: at('wash', t.wash),
  };
}

function renderTokyoSchemeBlock(scheme: 'light' | 'dark'): string {
  const d = buildTokyoDeclarations(scheme);
  const t = TOKENS[scheme];
  const at = (leaf: string, value: string) => pick(`${scheme}.${leaf}`, value);
  const topComment =
    scheme === 'light' ? TOKYO_LIGHT_TOP_COMMENT : TOKYO_DARK_TOP_COMMENT;
  const mutedTextComment =
    scheme === 'light'
      ? TOKYO_LIGHT_MUTED_TEXT_COMMENT
      : TOKYO_DARK_MUTED_TEXT_COMMENT;
  const accentTextComment =
    scheme === 'light'
      ? TOKYO_LIGHT_ACCENT_TEXT_COMMENT
      : TOKYO_DARK_ACCENT_TEXT_COMMENT;
  const redTextComment =
    scheme === 'light'
      ? TOKYO_LIGHT_RED_TEXT_COMMENT
      : TOKYO_DARK_RED_TEXT_COMMENT;
  return [
    topComment,
    `  --tk-chrome: ${d.chrome};`,
    `  --tk-bg: ${d.bg};`,
    `  --tk-panel: ${d.panel};`,
    `  --tk-card: ${d.card};`,
    `  --tk-inset: ${d.inset};`,
    `  --tk-overlay: ${d.overlay};`,
    `  --tk-border: ${d.border};`,
    `  --tk-border-soft: ${d.borderSoft};`,
    `  --tk-border-on-card: ${d.borderOnCard};`,
    `  --tk-control-edge: ${d.controlEdge};`,
    `  --tk-soft-on-card: ${d.softOnCard};`,
    `  --tk-fg: ${d.fg};`,
    `  --tk-muted: ${d.muted};`,
    mutedTextComment,
    `  --tk-muted-text: ${d.mutedText};`,
    `  --tk-muted-on-card: ${d.mutedOnCard};`,
    `  --tk-accent: ${d.accent};`,
    accentTextComment,
    `  --tk-accent-text: ${d.accentText};`,
    `  --tk-badge-text: ${d.badgeText};`,
    redTextComment,
    `  --tk-red-text: ${d.redText};`,
    `  --tk-green: ${d.green};`,
    `  --tk-green-text: ${d.okText};`,
    `  --tk-red: ${d.red};`,
    `  --tk-amber: ${d.amber};`,
    `  --tk-amber-text: ${d.amberText};`,
    `  --tk-purple: ${d.purple};`,
    `  --tk-cyan: ${d.cyan};`,
    `  --tk-grid-line: ${d.gridLine};`,
    `  --tk-dot-ok: ${d.dotOk};`,
    `  --tk-dot-warn: ${d.dotWarn};`,
    `  --tk-dot-bad: ${d.dotBad};`,
    `  --tk-raised: ${at('surface.raised', t.surface.raised)};`,
    ...t.surfaceRamp.map(
      (v, i) => `  --tk-surface-${i + 1}: ${at(`surfaceRamp.${i}`, v)};`
    ),
    ...t.textRamp.map(
      (v, i) => `  --tk-text-${i + 1}: ${at(`textRamp.${i}`, v)};`
    ),
    ...t.lineRamp.map(
      (v, i) => `  --tk-line-${i + 1}: ${at(`lineRamp.${i}`, v)};`
    ),
    ...HUES.map(h => `  --tk-fill-${h}: ${at(`hue.${h}`, t.hue[h])};`),
    ...HUES.map(
      h => `  --tk-fill-${h}-hover: ${at(`hueHover.${h}`, t.hueHover[h])};`
    ),
    ...HUES.map(
      h => `  --tk-on-fill-${h}: ${at(`hueOnFill.${h}`, t.hueOnFill[h])};`
    ),
    ...HUES.map(h => `  --tk-text-${h}: ${at(`hueText.${h}`, t.hueText[h])};`),
    ...HUES.map(
      h =>
        `  --tk-text-${h}-small: ${at(`hueTextSmall.${h}`, t.hueTextSmall[h])};`
    ),
    ...HUES.map(
      h =>
        `  --tk-text-${h}-vivid: ${at(`hueTextVivid.${h}`, t.hueTextVivid[h])};`
    ),
    '',
    `  --tk-wash: ${d.wash};`,
  ].join('\n');
}

function renderMantinePins(scheme: 'light' | 'dark'): string {
  return Object.entries(mantinePins(scheme))
    .map(([name, value]) => `  ${name}: ${value};`)
    .join('\n');
}

/**
 * Splices `body` between one BEGIN/END marker pair, replacing whatever
 * currently sits there. The markers themselves are left untouched --
 * everything else in tokyo-theme.css is hand-authored and never moves.
 *
 * `endMarker` text is shared by every scheme block, so a lone `indexOf`
 * for it would happily match a later block's END if this block's own END
 * were missing -- that read would splice `body` across the boundary into
 * the next block instead of failing. The next-BEGIN check below closes
 * that: any BEGIN marker between this one and the matched END means the
 * END wasn't this block's, so it throws instead of splicing silently.
 */
export function spliceGenerated(
  css: string,
  beginMarker: string,
  body: string
): string {
  const endMarker = '/* END GENERATED */';
  const beginIdx = css.indexOf(beginMarker);
  if (beginIdx === -1) {
    throw new Error(`tokyo-theme.css: marker not found: ${beginMarker}`);
  }
  if (css.indexOf(beginMarker, beginIdx + 1) !== -1) {
    throw new Error(`tokyo-theme.css: duplicate marker: ${beginMarker}`);
  }
  const afterBegin = beginIdx + beginMarker.length;
  const endIdx = css.indexOf(endMarker, afterBegin);
  if (endIdx === -1) {
    throw new Error(`tokyo-theme.css: no END GENERATED after ${beginMarker}`);
  }
  const nextBeginPattern = /\/\* BEGIN GENERATED:.*?\*\//g;
  nextBeginPattern.lastIndex = afterBegin;
  const nextBegin = nextBeginPattern.exec(css);
  if (nextBegin !== null && nextBegin.index < endIdx) {
    throw new Error(
      `tokyo-theme.css: no END GENERATED before the next BEGIN marker after ${beginMarker}`
    );
  }
  return css.slice(0, afterBegin) + '\n' + body + '\n  ' + css.slice(endIdx);
}

const BODY_RULE_PATTERN = /\nbody \{[^}]*\}\n\n/;

/**
 * Unlike tui-kit's theme.css (fully overwritten by `soribashi build` on
 * every run, so a plain append is idempotent by construction),
 * tokyo-theme.css persists across runs: `generateTokyoThemeCss` re-reads
 * whatever is already on disk. A blind append would duplicate the fragment
 * on the second run, so this replaces it in place once the markers exist
 * and only falls back to the body-rule anchor -- the kit's own `body` rule
 * keeps background/type, this fragment carries only smoothing -- on the
 * first run.
 */
function upsertFontSmoothingFragment(css: string): string {
  const beginIdx = css.indexOf(FONT_SMOOTHING_BEGIN_MARKER);
  if (beginIdx !== -1) {
    const endIdx = css.indexOf(FONT_SMOOTHING_END_MARKER, beginIdx);
    if (endIdx === -1) {
      throw new Error(
        `tokyo-theme.css: found ${FONT_SMOOTHING_BEGIN_MARKER} without matching ${FONT_SMOOTHING_END_MARKER}`
      );
    }
    return (
      css.slice(0, beginIdx) +
      renderFontSmoothing() +
      css.slice(endIdx + FONT_SMOOTHING_END_MARKER.length)
    );
  }
  const match = BODY_RULE_PATTERN.exec(css);
  if (match === null) {
    throw new Error(
      'tokyo-theme.css: no body rule found to anchor the font-smoothing fragment after'
    );
  }
  const insertAt = match.index + match[0].length;
  return (
    css.slice(0, insertAt) +
    renderFontSmoothing() +
    '\n\n' +
    css.slice(insertAt)
  );
}

function generateTokyoThemeCss(): string {
  let css = readFileSync(TOKYO_THEME_CSS, 'utf8');
  css = spliceGenerated(
    css,
    '/* BEGIN GENERATED: tokyo tokens light */',
    renderTokyoSchemeBlock('light')
  );
  css = spliceGenerated(
    css,
    '/* BEGIN GENERATED: tokyo tokens dark */',
    renderTokyoSchemeBlock('dark')
  );
  css = spliceGenerated(
    css,
    '/* BEGIN GENERATED: mantine pins light */',
    renderMantinePins('light')
  );
  css = spliceGenerated(
    css,
    '/* BEGIN GENERATED: mantine pins dark */',
    renderMantinePins('dark')
  );
  css = upsertFontSmoothingFragment(css);
  return css;
}

function copyFont(): void {
  for (const target of FONT_TARGETS) {
    copyFileSync(FONT_SOURCE, target);
  }
}

function main() {
  writeFileSync(TUI_KIT_TOKENS_TS, generateTuiKitTokens());
  writeFileSync(TOKYO_THEME_CSS, generateTokyoThemeCss());
  copyFont();
}

// Guarded so the test suite can import spliceGenerated without triggering a
// write-to-disk as a side effect of the import.
if (import.meta.main) {
  main();
}
