import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { RADIX, type Scale12 } from '../src/radix.ts';
import { HUE_SCALE, HUES, type HueName } from '../src/values.ts';

const OUT = join(import.meta.dirname, '..', '..', 'tokyo', 'src', 'ramps.ts');

// Mantine reads tuple index 6 as the light primary and, with
// primaryShade.dark = 3 in packages/tokyo/src/theme.ts, index 3 as the dark
// primary; both picks put Radix step 9 there. Radix dark scales run darkest
// to lightest, Mantine tuples lightest to darkest, hence the reversed pick.
const DAY_PICK = [1, 3, 4, 5, 6, 7, 9, 10, 11, 12] as const;
const NIGHT_PICK = [12, 11, 10, 9, 8, 7, 6, 5, 4, 3] as const;
const GRAY_PICK = [2, 3, 4, 6, 7, 8, 11, 11, 12, 12] as const;
const DARK_PICK = [12, 11, 11, 9, 8, 4, 3, 2, 1, 1] as const;

const pick = (scale: Scale12, steps: readonly number[]) =>
  steps.map(s => scale[s - 1]!);

function tuple(name: string, values: string[]): string {
  return [`  ${name}: [`, ...values.map(v => `    '${v}',`), '  ],'].join('\n');
}

function render(): string {
  const lines: string[] = [
    '/* GENERATED by packages/tokens/scripts/generate-ramps.ts; do not edit. */',
    "import type { MantineColorsTuple } from '@mantine/core';",
    '',
    '/**',
    ' * Radix Colors scales (packages/tokens/src/radix.ts) picked down to the ten',
    ' * shades Mantine reads: light 1 3 4 5 6 7 9 10 11 12, dark 12 11 10 9 8 7 6',
    ' * 5 4 3, so step 9 sits on the primary shade in both schemes. The pins',
    ' * that override Mantine derivations live in tokyo-theme.css (generated',
    ' * from packages/tokens/src/mantine-pins.ts). Regenerate with',
    ' * `bun run tokens:ramps`.',
    ' */',
    'export const tokyoRamps = {',
  ];
  for (const hue of HUES as readonly HueName[]) {
    const scale = RADIX[HUE_SCALE[hue]];
    lines.push(tuple(`${hue}Day`, pick(scale.light, DAY_PICK)));
    lines.push(tuple(`${hue}Night`, pick(scale.dark, NIGHT_PICK)));
  }
  lines.push(tuple('grayDay', pick(RADIX.slate.light, GRAY_PICK)));
  lines.push(tuple('darkNight', pick(RADIX.slate.dark, DARK_PICK)));
  lines.push('} as const satisfies Record<string, readonly string[]>;', '');
  lines.push('export type TokyoRampName = keyof typeof tokyoRamps;', '');
  lines.push(
    'export const ramp = (name: TokyoRampName): MantineColorsTuple =>'
  );
  lines.push('  tokyoRamps[name] as unknown as MantineColorsTuple;', '');
  return lines.join('\n');
}

if (import.meta.main) {
  writeFileSync(OUT, render());
}
