import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';

const require = createRequire(import.meta.url);
const PKG_DIR = dirname(require.resolve('@radix-ui/colors/package.json'));
const OUT = join(import.meta.dirname, '..', 'src', 'radix.ts');

const SCALES = [
  'slate',
  'indigo',
  'teal',
  'crimson',
  'orange',
  'purple',
  'cyan',
  'amber',
] as const;

function steps(file: string, name: string): string[] {
  const css = readFileSync(join(PKG_DIR, file), 'utf8');
  const out: string[] = [];
  for (let i = 1; i <= 12; i++) {
    const m = new RegExp(`--${name}-${i}: (#[0-9a-f]{6});`).exec(css);
    if (!m) throw new Error(`${file}: no --${name}-${i}`);
    out.push(m[1]!);
  }
  return out;
}

function tuple(values: string[]): string {
  return '[' + values.map(v => `'${v}'`).join(', ') + ']';
}

function render(): string {
  const version = (
    JSON.parse(readFileSync(join(PKG_DIR, 'package.json'), 'utf8')) as {
      version: string;
    }
  ).version;
  const lines = [
    '/* GENERATED by packages/tokens/scripts/generate-radix.ts from @radix-ui/colors; do not edit. */',
    '',
    `export const RADIX_VERSION = '${version}';`,
    '',
    `export const RADIX_SCALES = [${SCALES.map(s => `'${s}'`).join(', ')}] as const;`,
    'export type RadixScaleName = (typeof RADIX_SCALES)[number];',
    '',
    'export type Scale12 = readonly [',
    '  string, string, string, string, string, string,',
    '  string, string, string, string, string, string,',
    '];',
    '',
    'export const RADIX: Record<RadixScaleName, { light: Scale12; dark: Scale12 }> = {',
  ];
  for (const name of SCALES) {
    lines.push(`  ${name}: {`);
    lines.push(`    light: ${tuple(steps(`${name}.css`, name))},`);
    lines.push(`    dark: ${tuple(steps(`${name}-dark.css`, name))},`);
    lines.push('  },');
  }
  lines.push('};', '');
  return lines.join('\n');
}

if (import.meta.main) {
  writeFileSync(OUT, render());
}
