import type { CommandArg, CommandNode } from "../../lib/command-tree.ts";

export type CommonFlags = { flags: Set<string>; href: string };

/**
 * Escape characters MDX would otherwise parse as JSX/expression syntax when
 * they show up in free-text prose (descriptions, hints). Order matters: `&`
 * must be escaped first so the entities inserted below aren't re-escaped.
 */
export function escapeMdxText(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/\{/g, "&#123;")
    .replace(/\}/g, "&#125;");
}

export function slugArg(name: string): string {
  return name.toLowerCase().trim().replace(/\s+/g, "-");
}

export function renderUsage(path: string[], args?: CommandArg[]): string {
  const positionals = (args ?? [])
    .filter((a) => !a.flag)
    .map((a) => `<${slugArg(a.name)}>`);
  const hasFlags = (args ?? []).some((a) => a.flag);
  const line = ["rt", ...path, ...positionals, hasFlags ? "[flags]" : ""]
    .filter(Boolean)
    .join(" ");
  return ["## Usage", "", "```bash", line, "```", ""].join("\n");
}

export function renderArgsTable(
  args: CommandArg[] | undefined,
  common: CommonFlags,
): string {
  if (!args || args.length === 0) return "";
  const rows = args.map((a) => {
    const token = a.flag ?? `<${slugArg(a.name)}>`;
    const label = a.flag && common.flags.has(a.flag)
      ? `[\`${token}\`](${common.href})`
      : `\`${token}\``;
    const def = a.default === undefined ? "" : `\`${String(a.default)}\``;
    const hint = escapeMdxText(a.hint ?? "");
    return `| ${label} | ${a.type} | ${def} | ${hint} |`;
  });
  return [
    "## Arguments & flags",
    "",
    "| Flag / Arg | Type | Default | Description |",
    "| --- | --- | --- | --- |",
    ...rows,
    "",
  ].join("\n");
}

export type RenderOpts = {
  common: CommonFlags;
  sourceBase: string;
  hasPartial: (relPath: string) => boolean;
};

export function sourceLink(node: CommandNode, opts: RenderOpts): string {
  if (!node.module) return "";
  const file = node.module.replace(/^\.\//, ""); // "./commands/x.ts" -> "commands/x.ts"
  const label = node.fn ? `${file} › ${node.fn}` : file;
  const url = opts.sourceBase.replace(/\/$/, "") + "/" + file;
  return `_See code: [${label}](${url})_\n`;
}

export function renderSubcommandsTable(node: CommandNode, path: string[]): string {
  const subs = node.subcommands;
  if (!subs) return "";
  const visible = Object.entries(subs).filter(([, n]) => !n.hidden && !n.devOnly);
  if (visible.length === 0) return "";
  const rows = visible.map(
    ([name, n]) => `| [\`${name}\`](${name}) | ${escapeMdxText(n.description)} |`,
  );
  return ["## Subcommands", "", "| Command | Description |", "| --- | --- |", ...rows, ""].join("\n");
}

export function renderPage(
  node: CommandNode,
  path: string[],
  relPath: string,
  opts: RenderOpts,
): string {
  const name = path[path.length - 1] ?? "rt";
  const frontMatter = [
    "---",
    `title: rt ${path.join(" ")}`,
    `sidebar_label: ${name}`,
    "---",
    "",
  ].join("\n");

  const breadcrumb = "`" + ["rt", ...path].join(" › ") + "`\n";
  const heading = `# rt ${path.join(" ")}\n`;
  const desc = escapeMdxText(node.description) + "\n";
  const usage = renderUsage(path, node.args);
  const argsTable = renderArgsTable(node.args, opts.common);
  const aliases =
    node.aliases && node.aliases.length
      ? `**Aliases:** ${node.aliases.map((a) => `\`${a}\``).join(", ")}\n`
      : "";
  const subs = renderSubcommandsTable(node, path);
  const src = sourceLink(node, opts);

  const partial = opts.hasPartial(relPath)
    ? [
        `import Notes from '@site/docs/reference/_partials/${relPath}.mdx';`,
        "",
        "## Examples & notes",
        "",
        "<Notes />",
        "",
      ].join("\n")
    : "";

  return [
    frontMatter,
    heading,
    breadcrumb,
    desc,
    usage,
    argsTable,
    aliases,
    subs,
    src,
    partial,
    "{/* generated by scripts/gen-docs.ts; edit prose in _partials, not here */}",
    "",
  ]
    .filter((s) => s !== "")
    .join("\n");
}
