#!/usr/bin/env bun
// Walks `dist/` (a finished `vite build` output) and writes
// `src/server/embedded/generated/manifest.ts`: one `with { type: 'file' }`
// import per emitted file, plus a request-path -> file map. Vite's hashed
// filenames mean that map can't be hand-written -- it has to be regenerated
// after every build. Run as the first step of `build:binary`, before
// `bun build --compile`, which is what actually embeds the referenced files
// into the binary.
import { mkdirSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, sep } from 'node:path';

const repoRoot = join(import.meta.dir, '..');
const distDir = join(repoRoot, 'dist');
const outFile = join(repoRoot, 'src/server/embedded/generated/manifest.ts');
const outDir = dirname(outFile);

function walk(dir: string): string[] {
  return readdirSync(dir).flatMap(entry => {
    const full = join(dir, entry);
    return statSync(full).isDirectory() ? walk(full) : [full];
  });
}

const files = walk(distDir).sort();
if (files.length === 0) {
  throw new Error(
    `No files found under ${distDir} -- run \`vite build\` first.`
  );
}

const indexHtmlAbs = join(distDir, 'index.html');
if (!files.includes(indexHtmlAbs)) {
  throw new Error(`${indexHtmlAbs} is missing from the build output.`);
}

// Import specifiers and manifest keys both need forward slashes regardless
// of host OS; node:path gives back the platform separator.
const toPosix = (p: string) => p.split(sep).join('/');

const importSpecifierFor = (absPath: string) => {
  const rel = toPosix(relative(outDir, absPath));
  return rel.startsWith('.') ? rel : `./${rel}`;
};
const urlPathFor = (absPath: string) =>
  '/' + toPosix(relative(distDir, absPath));

const lines: string[] = [
  '// AUTO-GENERATED by scripts/generate-embedded-assets.ts -- do not edit by',
  '// hand. Gitignored: regenerated by `bun run build:binary` immediately',
  '// after `vite build`, right before `bun build --compile` embeds the files',
  '// these imports reference into the compiled binary.',
  '',
  "import type { EmbeddedManifest } from '../types';",
  '',
];

files.forEach((absPath, i) => {
  lines.push(
    `import asset${i} from '${importSpecifierFor(absPath)}' with { type: 'file' };`
  );
});

lines.push('', 'export const manifest: EmbeddedManifest = {');
lines.push(`  indexHtmlPath: asset${files.indexOf(indexHtmlAbs)},`);
lines.push('  files: {');
files.forEach((absPath, i) => {
  lines.push(`    ${JSON.stringify(urlPathFor(absPath))}: asset${i},`);
});
lines.push('  },');
lines.push('};');
lines.push('');

mkdirSync(outDir, { recursive: true });
writeFileSync(outFile, lines.join('\n'));

console.log(
  `Generated ${relative(repoRoot, outFile)} for ${files.length} embedded files.`
);
