import type { TiltResource } from "./lib";

/**
 * Build the placeholder map dynamically from app names.
 * Always includes 'repo' → REPO_ROOT, plus port_<name> → PORT_<NAME> for each app.
 */
function buildPlaceholders(
  appNames: string[],
): Record<string, string> {
  const placeholders: Record<string, string> = { repo: "REPO_ROOT" };
  for (const name of appNames) {
    placeholders[`port_${name}`] = `PORT_${name.toUpperCase()}`;
  }
  return placeholders;
}

/** Shell keywords that indicate a real multi-line script (not a one-liner). */
const SCRIPT_KEYWORDS = /\b(if|then|else|elif|fi|for|do|done|while|case|esac)\b/;

/**
 * Normalize a command string for the Tiltfile.
 *
 * If the command is a real multi-line shell script (contains if/then/fi etc.),
 * leave it as-is. Otherwise collapse indented continuation lines into a single
 * space-separated line. This lets the config use readable multiline template
 * literals for long commands without breaking the generated shell command.
 */
export function normalizeCmd(cmd: string): string {
  if (SCRIPT_KEYWORDS.test(cmd)) return cmd;
  // Collapse newline + leading whitespace into a single space
  return cmd.replace(/\n\s+/g, " ").trim();
}

/**
 * Render a Python-quoted string with .format() appended
 * to resolve {repo}, {port_*} placeholders.
 */
function pyCmd(s: string, formatKwargs: string): string {
  const normalized = normalizeCmd(s);
  const esc = normalized.replace(/'/g, "\\'");
  if (normalized.includes("\n")) {
    return `'''\n${normalized}\n    '''.format(${formatKwargs})`;
  }
  return `'${esc}'.format(${formatKwargs})`;
}

/**
 * Render a Python list of strings, e.g. ['a', 'b'].
 */
function pyList(items: string[]): string {
  return `[${items.map((s) => `'${s}'`).join(", ")}]`;
}

/**
 * Render a link string as a Python expression.
 * Replaces {port_*} placeholders with `str(VAR)` concatenation.
 * e.g. "http://localhost:{port_backend}" →
 *      'http://localhost:' + str(PORT_BACKEND)
 */
function pyLinkExpr(
  link: string,
  placeholders: Record<string, string>,
): string {
  const parts: string[] = [];
  const re = /\{(\w+)\}/g;
  let match: RegExpExecArray | null;
  let lastIndex = 0;

  re.lastIndex = 0;
  while ((match = re.exec(link)) !== null) {
    const before = link.slice(lastIndex, match.index);
    if (before) parts.push(`'${before}'`);
    const varName = placeholders[match[1]];
    if (varName) {
      parts.push(`str(${varName})`);
    } else {
      // Unknown placeholder, keep literal
      parts.push(`'${match[0]}'`);
    }
    lastIndex = re.lastIndex;
  }
  const tail = link.slice(lastIndex);
  if (tail) parts.push(`'${tail}'`);

  return parts.length === 1 ? parts[0] : parts.join(" + ");
}

/**
 * Render links as a Python list expression with variable interpolation.
 */
function pyLinks(
  links: string[],
  placeholders: Record<string, string>,
): string {
  return `[${links.map((l) => pyLinkExpr(l, placeholders)).join(", ")}]`;
}

/**
 * Render a single local_resource() Starlark call from a TiltResource.
 */
function renderResource(
  r: TiltResource,
  formatKwargs: string,
  placeholders: Record<string, string>,
): string {
  const cmdKey = r.cmdType === "serve" ? "serve_cmd" : "cmd";
  const lines: string[] = [
    `local_resource(`,
    `    '${r.name}',`,
    `    ${cmdKey}=${pyCmd(r.cmd, formatKwargs)},`,
    `    labels=${pyList(r.labels)},`,
  ];

  if (r.autoInit === false) {
    lines.push(`    auto_init=False,`);
  }
  if (r.deps?.length) {
    lines.push(`    resource_deps=${pyList(r.deps)},`);
  }
  if (r.links?.length) {
    lines.push(`    links=${pyLinks(r.links, placeholders)},`);
  }

  lines.push(`)`);
  return lines.join("\n");
}

/**
 * Generates Tiltfile content from a TiltResource array and app names.
 *
 * The generated Tiltfile reads REPO_ROOT and PORT_* from env vars set by the
 * orchestrator, then defines each resource. Resources are grouped visually by
 * their first label with section comment headings.
 */
export function generateTiltfile(
  resources: TiltResource[],
  appNames: string[],
): string {
  const placeholders = buildPlaceholders(appNames);
  const formatKwargs = Object.entries(placeholders)
    .map(([k, v]) => `${k}=${v}`)
    .join(", ");

  const parts: string[] = [
    `# Auto-generated by dev-proxy orchestrator — do not edit`,
    ``,
    `REPO_ROOT = os.environ['REPO_ROOT']`,
  ];

  // Emit PORT_<NAME> env var readers dynamically
  for (const name of appNames) {
    const varName = `PORT_${name.toUpperCase()}`;
    const pad = " ".repeat(Math.max(0, 10 - name.length));
    parts.push(`${varName}${pad} = int(os.environ['${varName}'])`);
  }

  // Group resources by their first label and render with section headings
  let currentLabel = "";
  for (const r of resources) {
    const label = r.labels[0] ?? "";
    if (label !== currentLabel) {
      currentLabel = label;
      const title = label || "other";
      parts.push(``);
      parts.push(
        `# ── ${title.charAt(0).toUpperCase() + title.slice(1)} ${"─".repeat(Math.max(0, 55 - title.length))}`,
      );
    }
    parts.push(``);
    parts.push(renderResource(r, formatKwargs, placeholders));
  }

  return parts.join("\n") + "\n";
}
