import type { TiltResource } from "./lib";

/** Map of placeholder tokens to their Python variable names. */
const PLACEHOLDERS: Record<string, string> = {
  repo: "REPO_ROOT",
  port_backend: "PORT_BACKEND",
  port_portal: "PORT_PORTAL",
  port_frontend: "PORT_FRONTEND",
};

const FORMAT_KWARGS = Object.entries(PLACEHOLDERS)
  .map(([k, v]) => `${k}=${v}`)
  .join(", ");

/** Shell keywords that indicate a real multi-line script (not a one-liner). */
const SCRIPT_KEYWORDS = /\b(if|then|else|elif|fi|for|do|done|while|case|esac)\b/;

/**
 * Normalize a command string for the Tiltfile.
 *
 * If the command is a real multi-line shell script (contains if/then/fi etc.),
 * leave it as-is. Otherwise collapse indented continuation lines into a single
 * space-separated line. This lets the config use readable multiline template
 * literals for long commands without breaking the generated shell command.
 */
export function normalizeCmd(cmd: string): string {
  if (SCRIPT_KEYWORDS.test(cmd)) return cmd;
  // Collapse newline + leading whitespace into a single space
  return cmd.replace(/\n\s+/g, " ").trim();
}

/**
 * Render a Python-quoted string with .format() appended
 * to resolve {repo}, {port_*} placeholders.
 */
function pyCmd(s: string): string {
  const normalized = normalizeCmd(s);
  const esc = normalized.replace(/'/g, "\\'");
  if (normalized.includes("\n")) {
    return `'''\n${normalized}\n    '''.format(${FORMAT_KWARGS})`;
  }
  return `'${esc}'.format(${FORMAT_KWARGS})`;
}

/**
 * Render a Python list of strings, e.g. ['a', 'b'].
 */
function pyList(items: string[]): string {
  return `[${items.map((s) => `'${s}'`).join(", ")}]`;
}

/**
 * Render a link string as a Python expression.
 * Replaces {port_*} placeholders with `str(VAR)` concatenation.
 * e.g. "http://localhost:{port_backend}" →
 *      'http://localhost:' + str(PORT_BACKEND)
 */
function pyLinkExpr(link: string): string {
  // Split on placeholders, interleave string literals and variable references
  const parts: string[] = [];
  let remaining = link;
  const re = /\{(\w+)\}/g;
  let match: RegExpExecArray | null;
  let lastIndex = 0;

  re.lastIndex = 0;
  while ((match = re.exec(remaining)) !== null) {
    const before = remaining.slice(lastIndex, match.index);
    if (before) parts.push(`'${before}'`);
    const varName = PLACEHOLDERS[match[1]];
    if (varName) {
      parts.push(`str(${varName})`);
    } else {
      // Unknown placeholder, keep literal
      parts.push(`'${match[0]}'`);
    }
    lastIndex = re.lastIndex;
  }
  const tail = remaining.slice(lastIndex);
  if (tail) parts.push(`'${tail}'`);

  return parts.length === 1 ? parts[0] : parts.join(" + ");
}

/**
 * Render links as a Python list expression with variable interpolation.
 */
function pyLinks(links: string[]): string {
  return `[${links.map(pyLinkExpr).join(", ")}]`;
}

/**
 * Render a single local_resource() Starlark call from a TiltResource.
 */
function renderResource(r: TiltResource): string {
  const cmdKey = r.cmdType === "serve" ? "serve_cmd" : "cmd";
  const lines: string[] = [
    `local_resource(`,
    `    '${r.name}',`,
    `    ${cmdKey}=${pyCmd(r.cmd)},`,
    `    labels=${pyList(r.labels)},`,
  ];

  if (r.autoInit === false) {
    lines.push(`    auto_init=False,`);
  }
  if (r.deps?.length) {
    lines.push(`    resource_deps=${pyList(r.deps)},`);
  }
  if (r.links?.length) {
    lines.push(`    links=${pyLinks(r.links)},`);
  }

  lines.push(`)`);
  return lines.join("\n");
}

/**
 * Generates Tiltfile content from a TiltResource array.
 *
 * The generated Tiltfile reads REPO_ROOT and PORT_* from env vars set by the
 * orchestrator, then defines each resource. Resources are grouped visually by
 * their first label with section comment headings.
 */
export function generateTiltfile(resources: TiltResource[]): string {
  const parts: string[] = [
    `# Auto-generated by dev-proxy orchestrator — do not edit`,
    ``,
    `REPO_ROOT = os.environ['REPO_ROOT']`,
    `PORT_BACKEND  = int(os.environ['PORT_BACKEND'])`,
    `PORT_PORTAL = int(os.environ['PORT_PORTAL'])`,
    `PORT_FRONTEND = int(os.environ['PORT_FRONTEND'])`,
  ];

  // Group resources by their first label and render with section headings
  let currentLabel = "";
  for (const r of resources) {
    const label = r.labels[0] ?? "";
    if (label !== currentLabel) {
      currentLabel = label;
      const title = label || "other";
      parts.push(``);
      parts.push(
        `# ── ${title.charAt(0).toUpperCase() + title.slice(1)} ${"─".repeat(Math.max(0, 55 - title.length))}`,
      );
    }
    parts.push(``);
    parts.push(renderResource(r));
  }

  return parts.join("\n") + "\n";
}
