import { afterEach, beforeEach, describe, expect, spyOn, test } from "bun:test";
import { chmodSync, existsSync, mkdirSync, mkdtempSync, readFileSync, realpathSync, statSync, writeFileSync } from "fs";
import { tmpdir } from "os";
import { dirname, join } from "path";
import { skillsCheck, skillsCompile } from "../skills.ts";
import { compileSkill } from "../../lib/skills/compile.ts";
import { invocableRoster, loadAttachment, loadStepSource } from "../../lib/skills/sources.ts";
import type { PluginRoots } from "../../lib/skills/sources.ts";
import type { VerbDef } from "../../lib/skills/types.ts";

function writeFile(path: string, content: string): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
}

const WATCH_CI_SKILL_MD = `---
name: watch-ci
description: "Watch CI until it goes green"
type: pipeline-step
allowed-tools:
  - "Bash(gh:*)"
  - "Read"
slots:
  domain: { contract: "watch-ci-domain@1" }
  forge: { contract: "ci-forge@1", required: true }
---

Poll the pipeline every 30s and report status. See \${CLAUDE_SKILL_DIR}/scripts/ci-watch.sh for the poller.
`;

const WATCH_CI_SCRIPT = "#!/bin/sh\necho polling\n";

const DOMAIN_SKILL_MD = `---
name: watch-ci-domain
description: "Domain rules for watch-ci"
metadata:
  provides: "watch-ci-domain@1"
allowed-tools:
  - "Read(\${CLAUDE_SKILL_DIR}/ci-config.json)"
---

Domain rules live at \${CLAUDE_SKILL_DIR}/ci-config.json for details.
`;

const CI_CONFIG_JSON = `{ "noisy": ["flaky-job"] }\n`;

const FORGE_SKILL_MD = `---
name: gitlab-forge
description: "Talk to GitLab via glab"
metadata:
  provides: "ci-forge@1"
allowed-tools:
  - "Bash(glab:*)"
---

Talk to GitLab via glab.
`;

const STUBS_JSONC = `{
  "verbs": {
    "watch-ci": {
      "engine": "watch-ci",
      "description": "Use when watching or triaging CI."
    }
  }
}
`;

function manifestJsonc(team: string, withForge: boolean): string {
  const bindings = withForge
    ? `{
      "domain": "acme:watch-ci-domain",
      "forge": "mattstack:gitlab-forge"
    }`
    : `{
      "domain": "acme:watch-ci-domain"
    }`;
  return `// GENERATED by merge-manifests.sh -- do not hand-edit;
// provenance (binding <- source):
//   mattstack:watch-ci domain <- ${team}@${team}
{
  "bindings": {
    "mattstack:watch-ci": ${bindings}
  }
}
`;
}

/**
 * Fixture "mattstack home" root: plugins/<name>/ mirrors resolvePluginRoots()'s
 * real shape (dir + .claude-plugin/plugin.json) so skillsCompile's test-mode
 * root resolution and the golden compile below walk identical trees.
 */
function makeMattstackDir(): string {
  const dir = realpathSync(mkdtempSync(join(tmpdir(), "rt-skills-cli-mattstack-")));

  const mattstackPluginDir = join(dir, "plugins", "mattstack");
  writeFile(join(mattstackPluginDir, ".claude-plugin", "plugin.json"), JSON.stringify({ version: "1.2.0" }));
  writeFile(join(mattstackPluginDir, "skills", "pipeline", "watch-ci", "SKILL.md"), WATCH_CI_SKILL_MD);
  writeFile(join(mattstackPluginDir, "skills", "pipeline", "watch-ci", "scripts", "ci-watch.sh"), WATCH_CI_SCRIPT);
  chmodSync(join(mattstackPluginDir, "skills", "pipeline", "watch-ci", "scripts", "ci-watch.sh"), 0o755);
  writeFile(join(mattstackPluginDir, "skills", "gitlab-forge", "SKILL.md"), FORGE_SKILL_MD);

  const acmePluginDir = join(dir, "plugins", "acme");
  writeFile(join(acmePluginDir, ".claude-plugin", "plugin.json"), JSON.stringify({ version: "0.3.0" }));
  writeFile(join(acmePluginDir, "attachments", "watch-ci-domain", "SKILL.md"), DOMAIN_SKILL_MD);
  writeFile(join(acmePluginDir, "attachments", "watch-ci-domain", "ci-config.json"), CI_CONFIG_JSON);

  return dir;
}

function makePackDir(): string {
  const dir = realpathSync(mkdtempSync(join(tmpdir(), "rt-skills-cli-pack-")));
  writeFile(join(dir, "pack", "stubs.jsonc"), STUBS_JSONC);
  return dir;
}

function makeManifest(team: string, withForge = true): string {
  const dir = realpathSync(mkdtempSync(join(tmpdir(), "rt-skills-cli-manifest-")));
  const path = join(dir, "skills.jsonc");
  writeFile(path, manifestJsonc(team, withForge));
  return path;
}

function computeGolden(mattstackDir: string) {
  const roots: PluginRoots = {
    byName: {
      mattstack: { dir: join(mattstackDir, "plugins", "mattstack"), version: "1.2.0" },
      acme: { dir: join(mattstackDir, "plugins", "acme"), version: "0.3.0" },
    },
  };
  const verb: VerbDef = { name: "watch-ci", engine: "watch-ci", description: "Use when watching or triaging CI." };
  const step = loadStepSource("watch-ci", roots);
  const domain = loadAttachment("acme:watch-ci-domain", "domain", roots);
  const forge = loadAttachment("mattstack:gitlab-forge", "forge", roots);
  const invocable = invocableRoster(roots);
  return compileSkill(verb, step, { domain, forge }, invocable);
}

let logSpy: ReturnType<typeof spyOn>;
let logs: string[];

beforeEach(() => {
  logs = [];
  logSpy = spyOn(console, "log").mockImplementation((...args: unknown[]) => {
    logs.push(args.map(String).join(" "));
  });
});

afterEach(() => {
  logSpy.mockRestore();
  // skillsCheck sets this on staleness; Bun ignores process.exitCode = undefined once
  // truthy, so 0 is the only value that clears it before the suite's own exit status.
  process.exitCode = 0;
});

/**
 * Expected/domain errors print a clean one-liner and process.exit(1) instead
 * of throwing a bare stack trace (matches commands/secrets.ts,
 * commands/settings-keys.ts). Mock process.exit to throw a sentinel so the
 * real test process never dies, and read the spies' recorded calls BEFORE
 * mockRestore() -- bun's mockRestore() clears .mock.calls, unlike jest's.
 */
async function runExpectingCleanExit(fn: () => Promise<void>): Promise<{ exitCode: number | undefined; errors: string[] }> {
  const errors: string[] = [];
  const exitSpy = spyOn(process, "exit").mockImplementation(() => {
    throw new Error("process.exit sentinel");
  });
  const errorSpy = spyOn(console, "error").mockImplementation((...args: unknown[]) => {
    errors.push(args.map(String).join(" "));
  });
  try {
    await fn();
    return { exitCode: undefined, errors };
  } catch {
    const exitCode = exitSpy.mock.calls.at(-1)?.[0] as number | undefined;
    return { exitCode, errors };
  } finally {
    exitSpy.mockRestore();
    errorSpy.mockRestore();
  }
}

describe("skillsCompile", () => {
  test("dry-run prints a would-write summary and writes nothing", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("t");

    await skillsCompile([
      "--team", "t",
      "--dry-run",
      "--pack-dir", packDir,
      "--mattstack-dir", mattstackDir,
      "--manifest", manifestPath,
      "--verb", "watch-ci",
    ]);

    const summary = logs.find((l) => /would write \d+ files/.test(l));
    expect(summary).toBeDefined();
    expect(summary).toContain("watch-ci");
    expect(existsSync(join(packDir, "skills", "watch-ci"))).toBe(false);
  });

  test("real run emits SKILL.md + vendored files matching a golden compile, byte for byte", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("t");

    await skillsCompile([
      "--team", "t",
      "--pack-dir", packDir,
      "--mattstack-dir", mattstackDir,
      "--manifest", manifestPath,
      "--verb", "watch-ci",
    ]);

    expect(logs.some((l) => l.includes("compiled watch-ci") && l.includes("3 files"))).toBe(true);

    const golden = computeGolden(mattstackDir);
    const outDir = join(packDir, "skills", "watch-ci");

    for (const file of golden.files) {
      const dest = join(outDir, file.path);
      expect(existsSync(dest)).toBe(true);
      const expected = "content" in file ? file.content : readFileSync(file.copyFrom, "utf8");
      expect(readFileSync(dest, "utf8")).toBe(expected);
    }

    const scriptPath = join(outDir, "scripts", "ci-watch.sh");
    expect(statSync(scriptPath).mode & 0o111).not.toBe(0);
  });

  test("missing required binding: clean one-line error naming verb and slot, exit 1, no partial write", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("t", false);

    const { exitCode, errors } = await runExpectingCleanExit(() =>
      skillsCompile([
        "--team", "t",
        "--pack-dir", packDir,
        "--mattstack-dir", mattstackDir,
        "--manifest", manifestPath,
        "--verb", "watch-ci",
      ]),
    );

    expect(exitCode).toBe(1);
    expect(errors).toHaveLength(1);
    expect(errors[0]).toStartWith("rt skills: ");
    expect(errors[0]).not.toContain("\n    at "); // no stack trace
    expect(errors[0]).toContain("watch-ci");
    expect(errors[0]).toContain("forge");
    expect(existsSync(join(packDir, "skills", "watch-ci"))).toBe(false);
  });

  test("unrecognized argument: clean one-line error, exit 1", async () => {
    const { exitCode, errors } = await runExpectingCleanExit(() =>
      skillsCompile(["--bogus-flag"]),
    );

    expect(exitCode).toBe(1);
    expect(errors).toHaveLength(1);
    expect(errors[0]).toStartWith("rt skills: ");
    expect(errors[0]).toContain("--bogus-flag");
  });

  test("unknown verb: clean one-line error, exit 1", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("t");

    const { exitCode, errors } = await runExpectingCleanExit(() =>
      skillsCompile([
        "--team", "t",
        "--pack-dir", packDir,
        "--mattstack-dir", mattstackDir,
        "--manifest", manifestPath,
        "--verb", "no-such-verb",
      ]),
    );

    expect(exitCode).toBe(1);
    expect(errors).toHaveLength(1);
    expect(errors[0]).toStartWith("rt skills: ");
    expect(errors[0]).toContain("no-such-verb");
  });

  test("absent manifest (no skills.jsonc names the team): clean one-line error, exit 1", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();

    const { exitCode, errors } = await runExpectingCleanExit(() =>
      skillsCompile([
        "--team", "t",
        "--pack-dir", packDir,
        "--mattstack-dir", mattstackDir,
        "--verb", "watch-ci",
      ]),
    );

    expect(exitCode).toBe(1);
    expect(errors).toHaveLength(1);
    expect(errors[0]).toStartWith("rt skills: ");
    expect(errors[0]).toContain("skills.jsonc");
  });

  test("default pack dir formula (--team + --mattstack-dir, no --pack-dir)", async () => {
    const mattstackDir = makeMattstackDir();
    const manifestPath = makeManifest("t");
    writeFile(join(mattstackDir, "teams", "t", "mattstack", "packs", "t", "pack", "stubs.jsonc"), STUBS_JSONC);

    await skillsCompile([
      "--team", "t",
      "--dry-run",
      "--mattstack-dir", mattstackDir,
      "--manifest", manifestPath,
    ]);

    expect(logs.some((l) => /would write \d+ files/.test(l) && l.includes("watch-ci"))).toBe(true);
  });

  test("default manifest lookup (--mattstack-dir only, no --manifest)", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    writeFile(join(mattstackDir, "repos", "some-repo", "skills.jsonc"), manifestJsonc("t", true));

    await skillsCompile([
      "--team", "t",
      "--dry-run",
      "--pack-dir", packDir,
      "--mattstack-dir", mattstackDir,
      "--verb", "watch-ci",
    ]);

    expect(logs.some((l) => /would write \d+ files/.test(l))).toBe(true);
  });
});

describe("skillsCheck", () => {
  test("reports current right after a compile", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("t");

    await skillsCompile([
      "--team", "t",
      "--pack-dir", packDir,
      "--mattstack-dir", mattstackDir,
      "--manifest", manifestPath,
      "--verb", "watch-ci",
    ]);
    logs = [];

    await skillsCheck([
      "--team", "t",
      "--pack-dir", packDir,
      "--mattstack-dir", mattstackDir,
      "--manifest", manifestPath,
      "--verb", "watch-ci",
    ]);

    expect(logs.some((l) => l.includes("watch-ci") && l.includes("current"))).toBe(true);
    expect(logs.some((l) => l.includes("stale"))).toBe(false);
    expect(process.exitCode).not.toBe(1);
  });

  test("hand-edited SKILL.md reports stale and exits 1", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("t");

    await skillsCompile([
      "--team", "t",
      "--pack-dir", packDir,
      "--mattstack-dir", mattstackDir,
      "--manifest", manifestPath,
      "--verb", "watch-ci",
    ]);

    const skillMdPath = join(packDir, "skills", "watch-ci", "SKILL.md");
    writeFileSync(skillMdPath, readFileSync(skillMdPath, "utf8") + "\nhand-edited drift\n");
    logs = [];

    await skillsCheck([
      "--team", "t",
      "--pack-dir", packDir,
      "--mattstack-dir", mattstackDir,
      "--manifest", manifestPath,
      "--verb", "watch-ci",
    ]);

    const staleLine = logs.find((l) => l.includes("stale"));
    expect(staleLine).toBeDefined();
    expect(staleLine).toContain("watch-ci");
    expect(staleLine).toContain("SKILL.md");
    expect(process.exitCode).toBe(1);
  });

  test("orphan file left over from a previous compile reports stale and exits 1", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("t");

    await skillsCompile([
      "--team", "t",
      "--pack-dir", packDir,
      "--mattstack-dir", mattstackDir,
      "--manifest", manifestPath,
      "--verb", "watch-ci",
    ]);

    writeFileSync(join(packDir, "skills", "watch-ci", "leftover.txt"), "stale content\n");
    logs = [];

    await skillsCheck([
      "--team", "t",
      "--pack-dir", packDir,
      "--mattstack-dir", mattstackDir,
      "--manifest", manifestPath,
      "--verb", "watch-ci",
    ]);

    const staleLine = logs.find((l) => l.includes("stale"));
    expect(staleLine).toBeDefined();
    expect(staleLine).toContain("watch-ci");
    expect(staleLine).toContain("leftover.txt");
    expect(process.exitCode).toBe(1);
  });

  test("never-compiled public verb (missing outDir) reports stale and exits 1", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("t");

    await skillsCheck([
      "--team", "t",
      "--pack-dir", packDir,
      "--mattstack-dir", mattstackDir,
      "--manifest", manifestPath,
      "--verb", "watch-ci",
    ]);

    const staleLine = logs.find((l) => l.includes("stale"));
    expect(staleLine).toBeDefined();
    expect(staleLine).toContain("watch-ci");
    expect(process.exitCode).toBe(1);
  });
});
