import { afterEach, beforeEach, describe, expect, spyOn, test } from "bun:test";
import { chmodSync, existsSync, mkdirSync, mkdtempSync, readFileSync, realpathSync, statSync, writeFileSync } from "fs";
import { tmpdir } from "os";
import { dirname, join } from "path";
import { skillsCheck, skillsCompile, skillsComposition, skillsPacks } from "../skills.ts";
import { compileSkill } from "../../lib/skills/compile.ts";
import { invocableRoster, loadAttachment, loadStepSource } from "../../lib/skills/sources.ts";
import type { PluginRoots } from "../../lib/skills/sources.ts";
import type { VerbDef } from "../../lib/skills/types.ts";

function writeFile(path: string, content: string): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
}

const WATCH_CI_SKILL_MD = `---
name: watch-ci
description: "Watch CI until it goes green"
type: pipeline-step
allowed-tools:
  - "Bash(gh:*)"
  - "Read"
slots:
  domain: { contract: "watch-ci-domain@1" }
  forge: { contract: "ci-forge@1", required: true }
---

Poll the pipeline every 30s and report status. See \${CLAUDE_SKILL_DIR}/scripts/ci-watch.sh for the poller.
`;

const WATCH_CI_SCRIPT = "#!/bin/sh\necho polling\n";

const DOMAIN_SKILL_MD = `---
name: watch-ci-domain
description: "Domain rules for watch-ci"
metadata:
  provides: "watch-ci-domain@1"
allowed-tools:
  - "Read(\${CLAUDE_SKILL_DIR}/ci-config.json)"
---

Domain rules live at \${CLAUDE_SKILL_DIR}/ci-config.json for details.
`;

const CI_CONFIG_JSON = `{ "noisy": ["flaky-job"] }\n`;

const FORGE_SKILL_MD = `---
name: gitlab-forge
description: "Talk to GitLab via glab"
metadata:
  provides: "ci-forge@1"
allowed-tools:
  - "Bash(glab:*)"
---

Talk to GitLab via glab.
`;

const STUBS_JSONC = `{
  "verbs": {
    "watch-ci": {
      "engine": "watch-ci",
      "description": "Use when watching or triaging CI."
    }
  }
}
`;

/**
 * A second, unrelated verb ("helper-verb") sharing watch-ci's engine, kept
 * out of surface.jsonc's public list so computeInternalRoster tags it
 * "acme:helper-verb" -- watch-ci's own description names that token,
 * which is exactly what lintInternalRoster flags (the only producer of
 * compileVerb's returned errors[], as opposed to a thrown failure).
 */
const STUBS_WITH_INTERNAL_REF = `{
  "verbs": {
    "watch-ci": {
      "engine": "watch-ci",
      "description": "Use when watching CI; see acme:helper-verb for internal detail."
    },
    "helper-verb": {
      "engine": "watch-ci",
      "description": "Internal helper, never surfaced."
    }
  }
}
`;

/** A second verb pointing at an engine that does not exist under any plugin root -- loadStepSource throws. */
const STUBS_TWO_VERBS = `{
  "verbs": {
    "watch-ci": {
      "engine": "watch-ci",
      "description": "Use when watching or triaging CI."
    },
    "broken": {
      "engine": "no-such-engine",
      "description": "Points at a retired engine."
    }
  }
}
`;

function manifestJsonc(team: string, withForge: boolean): string {
  const bindings = withForge
    ? `{
      "domain": "acme:watch-ci-domain",
      "forge": "mattstack:gitlab-forge"
    }`
    : `{
      "domain": "acme:watch-ci-domain"
    }`;
  return `// GENERATED by merge-manifests.sh -- do not hand-edit;
// provenance (binding <- source):
//   mattstack:watch-ci domain <- ${team}@${team}
{
  "bindings": {
    "mattstack:watch-ci": ${bindings}
  }
}
`;
}

/**
 * Fixture "mattstack home" root: plugins/<name>/ mirrors resolvePluginRoots()'s
 * real shape (dir + .claude-plugin/plugin.json) so skillsCompile's test-mode
 * root resolution and the golden compile below walk identical trees.
 */
function makeMattstackDir(): string {
  const dir = realpathSync(mkdtempSync(join(tmpdir(), "rt-skills-cli-mattstack-")));

  const mattstackPluginDir = join(dir, "plugins", "mattstack");
  writeFile(join(mattstackPluginDir, ".claude-plugin", "plugin.json"), JSON.stringify({ version: "1.2.0" }));
  writeFile(join(mattstackPluginDir, "skills", "pipeline", "watch-ci", "SKILL.md"), WATCH_CI_SKILL_MD);
  writeFile(join(mattstackPluginDir, "skills", "pipeline", "watch-ci", "scripts", "ci-watch.sh"), WATCH_CI_SCRIPT);
  chmodSync(join(mattstackPluginDir, "skills", "pipeline", "watch-ci", "scripts", "ci-watch.sh"), 0o755);
  writeFile(join(mattstackPluginDir, "skills", "gitlab-forge", "SKILL.md"), FORGE_SKILL_MD);

  const acmePluginDir = join(dir, "plugins", "acme");
  writeFile(join(acmePluginDir, ".claude-plugin", "plugin.json"), JSON.stringify({ version: "0.3.0" }));
  writeFile(join(acmePluginDir, "attachments", "watch-ci-domain", "SKILL.md"), DOMAIN_SKILL_MD);
  writeFile(join(acmePluginDir, "attachments", "watch-ci-domain", "ci-config.json"), CI_CONFIG_JSON);

  return dir;
}

function makePackDir(): string {
  const dir = realpathSync(mkdtempSync(join(tmpdir(), "rt-skills-cli-pack-")));
  writeFile(join(dir, "pack", "stubs.jsonc"), STUBS_JSONC);
  return dir;
}

function makeManifest(team: string, withForge = true): string {
  const dir = realpathSync(mkdtempSync(join(tmpdir(), "rt-skills-cli-manifest-")));
  const path = join(dir, "skills.jsonc");
  writeFile(path, manifestJsonc(team, withForge));
  return path;
}

/** domain is bound to a name nothing provides -- loadAttachment throws, exercising composition's per-slot degrade. */
function makeManifestDanglingDomain(): string {
  const dir = realpathSync(mkdtempSync(join(tmpdir(), "rt-skills-cli-manifest-")));
  const path = join(dir, "skills.jsonc");
  writeFile(path, `{
  "bindings": {
    "mattstack:watch-ci": {
      "domain": "acme:does-not-exist",
      "forge": "mattstack:gitlab-forge"
    }
  }
}
`);
  return path;
}

function computeGolden(mattstackDir: string) {
  const roots: PluginRoots = {
    byName: {
      mattstack: { dir: join(mattstackDir, "plugins", "mattstack"), version: "1.2.0" },
      acme: { dir: join(mattstackDir, "plugins", "acme"), version: "0.3.0" },
    },
  };
  const verb: VerbDef = { name: "watch-ci", engine: "watch-ci", description: "Use when watching or triaging CI." };
  const step = loadStepSource("watch-ci", roots);
  const domain = loadAttachment("acme:watch-ci-domain", "domain", roots);
  const forge = loadAttachment("mattstack:gitlab-forge", "forge", roots);
  const invocable = invocableRoster(roots);
  return compileSkill(verb, step, { domain, forge }, invocable);
}

let logSpy: ReturnType<typeof spyOn>;
let logs: string[];

beforeEach(() => {
  logs = [];
  logSpy = spyOn(console, "log").mockImplementation((...args: unknown[]) => {
    logs.push(args.map(String).join(" "));
  });
});

afterEach(() => {
  logSpy.mockRestore();
  // skillsCheck sets this on staleness; Bun ignores process.exitCode = undefined once
  // truthy, so 0 is the only value that clears it before the suite's own exit status.
  process.exitCode = 0;
});

/**
 * Expected/domain errors print a clean one-liner and process.exit(1) instead
 * of throwing a bare stack trace (matches commands/secrets.ts,
 * commands/settings-keys.ts). Mock process.exit to throw a sentinel so the
 * real test process never dies, and read the spies' recorded calls BEFORE
 * mockRestore() -- bun's mockRestore() clears .mock.calls, unlike jest's.
 */
async function runExpectingCleanExit(fn: () => Promise<void>): Promise<{ exitCode: number | undefined; errors: string[] }> {
  const errors: string[] = [];
  const exitSpy = spyOn(process, "exit").mockImplementation(() => {
    throw new Error("process.exit sentinel");
  });
  const errorSpy = spyOn(console, "error").mockImplementation((...args: unknown[]) => {
    errors.push(args.map(String).join(" "));
  });
  try {
    await fn();
    return { exitCode: undefined, errors };
  } catch {
    const exitCode = exitSpy.mock.calls.at(-1)?.[0] as number | undefined;
    return { exitCode, errors };
  } finally {
    exitSpy.mockRestore();
    errorSpy.mockRestore();
  }
}

describe("skillsCompile", () => {
  test("dry-run prints a would-write summary and writes nothing", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("t");

    await skillsCompile([
      "--team", "t",
      "--dry-run",
      "--pack-dir", packDir,
      "--mattstack-dir", mattstackDir,
      "--manifest", manifestPath,
      "--verb", "watch-ci",
    ]);

    const summary = logs.find((l) => /would write \d+ files/.test(l));
    expect(summary).toBeDefined();
    expect(summary).toContain("watch-ci");
    expect(existsSync(join(packDir, "skills", "watch-ci"))).toBe(false);
  });

  test("--preview prints the compiled body and writes nothing", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("t");

    await skillsCompile(["--pack", "t", "--verb", "watch-ci", "--preview",
      "--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath]);

    const out = logs.join("\n");
    expect(out).toContain("<!-- part: step source=");
    expect(out).not.toContain("compiled watch-ci (");
    expect(existsSync(join(packDir, "skills", "watch-ci"))).toBe(false);
  });

  test("--preview requires exactly one verb", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("t");

    const { exitCode, errors } = await runExpectingCleanExit(() =>
      skillsCompile(["--pack", "t", "--preview",
        "--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath]));

    expect(exitCode).toBe(1);
    expect(errors.join("\n")).toContain("--preview needs a single --verb");
  });

  test("--preview on a retired (surface-internal) verb leaves its stale output directory alone", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("t");
    // watch-ci is absent from surface.jsonc's public list, so it is internal/retired --
    // this is the transition-window state computeInternalRoster's own comment describes.
    writeFile(join(packDir, "pack", "surface.jsonc"), `{ "public": [] }\n`);
    // A stale output dir from an earlier (pre-retirement) real compile.
    writeFile(join(packDir, "skills", "watch-ci", "SKILL.md"), "stale\n");

    await skillsCompile(["--pack", "t", "--verb", "watch-ci", "--preview",
      "--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath]);

    expect(existsSync(join(packDir, "skills", "watch-ci"))).toBe(true);
  });

  test("--preview on a retired verb writes its status line to stderr, not stdout", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("t");
    writeFile(join(packDir, "pack", "surface.jsonc"), `{ "public": [] }\n`);

    const errors: string[] = [];
    const errorSpy = spyOn(console, "error").mockImplementation((...args: unknown[]) => {
      errors.push(args.map(String).join(" "));
    });
    try {
      await skillsCompile(["--pack", "t", "--verb", "watch-ci", "--preview",
        "--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath]);
    } finally {
      errorSpy.mockRestore();
    }

    // A caller piping --preview to a file must never see this status line:
    // it belongs on stderr, and stdout must stay empty.
    expect(logs.join("\n")).not.toContain("not compiled; roster entry retired");
    expect(errors.join("\n")).toContain("not compiled; roster entry retired");
  });

  test("retired verb in a pack that ALSO has a misplaced compiled dir: still nothing on stdout", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("t");
    writeFile(join(packDir, "pack", "surface.jsonc"), `{ "public": [] }\n`);
    // Registered on disk, absent from the public list, and NOT the requested
    // verb: exactly what the post-loop scan reports. A retired verb reaches
    // that scan by `continue` where a lint-erroring one returns before it, so
    // this is the same leak through the other doorway -- and the console reads
    // any non-empty stdout as the compiled body.
    writeFile(join(packDir, "skills", "stray-skill", "SKILL.md"), "# stray\n");

    const errorSpy = spyOn(console, "error").mockImplementation(() => {});
    try {
      await skillsCompile(["--pack", "t", "--verb", "watch-ci", "--preview",
        "--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath]);
    } finally {
      errorSpy.mockRestore();
    }

    expect(logs.join("\n")).toBe("");
  });

  test("real run emits SKILL.md + vendored files matching a golden compile, byte for byte", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("t");

    await skillsCompile([
      "--team", "t",
      "--pack-dir", packDir,
      "--mattstack-dir", mattstackDir,
      "--manifest", manifestPath,
      "--verb", "watch-ci",
    ]);

    expect(logs.some((l) => l.includes("compiled watch-ci") && l.includes("3 files"))).toBe(true);

    const golden = computeGolden(mattstackDir);
    const outDir = join(packDir, "skills", "watch-ci");

    for (const file of golden.files) {
      const dest = join(outDir, file.path);
      expect(existsSync(dest)).toBe(true);
      const expected = "content" in file ? file.content : readFileSync(file.copyFrom, "utf8");
      expect(readFileSync(dest, "utf8")).toBe(expected);
    }

    const scriptPath = join(outDir, "scripts", "ci-watch.sh");
    expect(statSync(scriptPath).mode & 0o111).not.toBe(0);
  });

  test("missing required binding: clean one-line error naming verb and slot, exit 1, no partial write", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("t", false);

    const { exitCode, errors } = await runExpectingCleanExit(() =>
      skillsCompile([
        "--team", "t",
        "--pack-dir", packDir,
        "--mattstack-dir", mattstackDir,
        "--manifest", manifestPath,
        "--verb", "watch-ci",
      ]),
    );

    expect(exitCode).toBe(1);
    expect(errors).toHaveLength(1);
    expect(errors[0]).toStartWith("rt skills: ");
    expect(errors[0]).not.toContain("\n    at "); // no stack trace
    expect(errors[0]).toContain("watch-ci");
    expect(errors[0]).toContain("forge");
    expect(existsSync(join(packDir, "skills", "watch-ci"))).toBe(false);
  });

  test("unrecognized argument: clean one-line error, exit 1", async () => {
    const { exitCode, errors } = await runExpectingCleanExit(() =>
      skillsCompile(["--bogus-flag"]),
    );

    expect(exitCode).toBe(1);
    expect(errors).toHaveLength(1);
    expect(errors[0]).toStartWith("rt skills: ");
    expect(errors[0]).toContain("--bogus-flag");
  });

  test("unknown verb: clean one-line error, exit 1", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("t");

    const { exitCode, errors } = await runExpectingCleanExit(() =>
      skillsCompile([
        "--team", "t",
        "--pack-dir", packDir,
        "--mattstack-dir", mattstackDir,
        "--manifest", manifestPath,
        "--verb", "no-such-verb",
      ]),
    );

    expect(exitCode).toBe(1);
    expect(errors).toHaveLength(1);
    expect(errors[0]).toStartWith("rt skills: ");
    expect(errors[0]).toContain("no-such-verb");
  });

  test("absent manifest (no skills.jsonc names the team): clean one-line error, exit 1", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();

    const { exitCode, errors } = await runExpectingCleanExit(() =>
      skillsCompile([
        "--team", "t",
        "--pack-dir", packDir,
        "--mattstack-dir", mattstackDir,
        "--verb", "watch-ci",
      ]),
    );

    expect(exitCode).toBe(1);
    expect(errors).toHaveLength(1);
    expect(errors[0]).toStartWith("rt skills: ");
    expect(errors[0]).toContain("skills.jsonc");
  });

  test("default pack dir formula (--team + --mattstack-dir, no --pack-dir)", async () => {
    const mattstackDir = makeMattstackDir();
    const manifestPath = makeManifest("t");
    writeFile(join(mattstackDir, "teams", "t", "mattstack", "packs", "t", "pack", "stubs.jsonc"), STUBS_JSONC);

    await skillsCompile([
      "--team", "t",
      "--dry-run",
      "--mattstack-dir", mattstackDir,
      "--manifest", manifestPath,
    ]);

    expect(logs.some((l) => /would write \d+ files/.test(l) && l.includes("watch-ci"))).toBe(true);
  });

  test("default manifest lookup (--mattstack-dir only, no --manifest)", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    writeFile(join(mattstackDir, "repos", "some-repo", "skills.jsonc"), manifestJsonc("t", true));

    await skillsCompile([
      "--team", "t",
      "--dry-run",
      "--pack-dir", packDir,
      "--mattstack-dir", mattstackDir,
      "--verb", "watch-ci",
    ]);

    expect(logs.some((l) => /would write \d+ files/.test(l))).toBe(true);
  });
});

describe("skillsCheck", () => {
  test("reports current right after a compile", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("t");

    await skillsCompile([
      "--team", "t",
      "--pack-dir", packDir,
      "--mattstack-dir", mattstackDir,
      "--manifest", manifestPath,
      "--verb", "watch-ci",
    ]);
    logs = [];

    await skillsCheck([
      "--team", "t",
      "--pack-dir", packDir,
      "--mattstack-dir", mattstackDir,
      "--manifest", manifestPath,
      "--verb", "watch-ci",
    ]);

    expect(logs.some((l) => l.includes("watch-ci") && l.includes("current"))).toBe(true);
    expect(logs.some((l) => l.includes("stale"))).toBe(false);
    expect(process.exitCode).not.toBe(1);
  });

  test("hand-edited SKILL.md reports stale and exits 1", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("t");

    await skillsCompile([
      "--team", "t",
      "--pack-dir", packDir,
      "--mattstack-dir", mattstackDir,
      "--manifest", manifestPath,
      "--verb", "watch-ci",
    ]);

    const skillMdPath = join(packDir, "skills", "watch-ci", "SKILL.md");
    writeFileSync(skillMdPath, readFileSync(skillMdPath, "utf8") + "\nhand-edited drift\n");
    logs = [];

    await skillsCheck([
      "--team", "t",
      "--pack-dir", packDir,
      "--mattstack-dir", mattstackDir,
      "--manifest", manifestPath,
      "--verb", "watch-ci",
    ]);

    const staleLine = logs.find((l) => l.includes("stale"));
    expect(staleLine).toBeDefined();
    expect(staleLine).toContain("watch-ci");
    expect(staleLine).toContain("SKILL.md");
    expect(process.exitCode).toBe(1);
  });

  test("orphan file left over from a previous compile reports stale and exits 1", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("t");

    await skillsCompile([
      "--team", "t",
      "--pack-dir", packDir,
      "--mattstack-dir", mattstackDir,
      "--manifest", manifestPath,
      "--verb", "watch-ci",
    ]);

    writeFileSync(join(packDir, "skills", "watch-ci", "leftover.txt"), "stale content\n");
    logs = [];

    await skillsCheck([
      "--team", "t",
      "--pack-dir", packDir,
      "--mattstack-dir", mattstackDir,
      "--manifest", manifestPath,
      "--verb", "watch-ci",
    ]);

    const staleLine = logs.find((l) => l.includes("stale"));
    expect(staleLine).toBeDefined();
    expect(staleLine).toContain("watch-ci");
    expect(staleLine).toContain("leftover.txt");
    expect(process.exitCode).toBe(1);
  });

  test("never-compiled public verb (missing outDir) reports stale and exits 1", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("t");

    await skillsCheck([
      "--team", "t",
      "--pack-dir", packDir,
      "--mattstack-dir", mattstackDir,
      "--manifest", manifestPath,
      "--verb", "watch-ci",
    ]);

    const staleLine = logs.find((l) => l.includes("stale"));
    expect(staleLine).toBeDefined();
    expect(staleLine).toContain("watch-ci");
    expect(process.exitCode).toBe(1);
  });
});

describe("skillsCheck --json", () => {
  test("emits one row per verb (never compiled)", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("acme");

    await skillsCheck(["--pack", "acme", "--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--json"]);

    const parsed = JSON.parse(logs.join("\n"));
    expect(parsed.pack).toBe("acme");
    expect(parsed.packDir).toBe(packDir);
    expect(parsed.verbs).toEqual([
      { name: "watch-ci", status: "never-compiled", staleFiles: [], orphanFiles: [] },
    ]);
  });

  test("prints ONLY json -- no human lines on stdout", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("acme");

    await skillsCheck(["--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--json"]);

    expect(() => JSON.parse(logs.join("\n"))).not.toThrow();
  });

  test("reports in-sync right after a compile", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("acme");

    await skillsCompile(["--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--verb", "watch-ci"]);
    logs = [];

    await skillsCheck(["--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--json"]);

    const parsed = JSON.parse(logs.join("\n"));
    expect(parsed.verbs).toEqual([
      { name: "watch-ci", status: "in-sync", staleFiles: [], orphanFiles: [] },
    ]);
  });

  test("separates staleFiles (content drift) from orphanFiles (leftover) instead of merging them", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("acme");

    await skillsCompile(["--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--verb", "watch-ci"]);
    const skillMdPath = join(packDir, "skills", "watch-ci", "SKILL.md");
    writeFileSync(skillMdPath, readFileSync(skillMdPath, "utf8") + "\nhand-edited drift\n");
    writeFileSync(join(packDir, "skills", "watch-ci", "leftover.txt"), "stale content\n");
    logs = [];

    await skillsCheck(["--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--json"]);

    const parsed = JSON.parse(logs.join("\n"));
    expect(parsed.verbs).toEqual([
      { name: "watch-ci", status: "stale", staleFiles: ["SKILL.md"], orphanFiles: ["leftover.txt"] },
    ]);
    expect(process.exitCode).toBe(1);
  });

  test("internal verb with missing outDir: internal-unchecked, and does not count as stale", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("acme");
    writeFile(join(packDir, "pack", "surface.jsonc"), `{ "public": [] }\n`);

    await skillsCheck(["--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--json"]);

    const parsed = JSON.parse(logs.join("\n"));
    expect(parsed.verbs).toEqual([
      { name: "watch-ci", status: "internal-unchecked", staleFiles: [], orphanFiles: [] },
    ]);
    expect(process.exitCode).not.toBe(1);
  });
});

describe("skillsCompile --json", () => {
  test("compiled verb: files + warnings reported, nothing written to disk", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("acme");

    await skillsCompile(["--pack", "acme", "--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--verb", "watch-ci", "--json"]);

    const parsed = JSON.parse(logs.join("\n"));
    expect(parsed.pack).toBe("acme");
    expect(parsed.verbs).toHaveLength(1);
    const verb = parsed.verbs[0];
    expect(verb.name).toBe("watch-ci");
    expect(verb.status).toBe("compiled");
    expect(verb.errors).toEqual([]);
    expect(verb.files.map((f: { path: string }) => f.path).sort()).toEqual([
      "SKILL.md",
      "parts/domain/ci-config.json",
      "scripts/ci-watch.sh",
    ]);
    expect(existsSync(join(packDir, "skills", "watch-ci"))).toBe(false);
    // A clean compile leaves the exit code unset: a caller reading it sees success.
    expect(process.exitCode).not.toBe(1);
  });

  test("internal (retired) verb: internal-skipped, no compile attempted, no disk write", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("acme");
    writeFile(join(packDir, "pack", "surface.jsonc"), `{ "public": [] }\n`);

    await skillsCompile(["--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--verb", "watch-ci", "--json"]);

    const parsed = JSON.parse(logs.join("\n"));
    expect(parsed.verbs).toEqual([
      { name: "watch-ci", status: "internal-skipped", files: [], warnings: [], errors: [] },
    ]);
  });

  test("lint-erroring verb (returned errors[]): errored with the message, other verbs unaffected -- command does not die", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    writeFile(join(packDir, "pack", "stubs.jsonc"), STUBS_WITH_INTERNAL_REF);
    writeFile(join(packDir, "pack", "surface.jsonc"), `{ "public": ["watch-ci"] }\n`);
    const manifestPath = makeManifest("acme");

    await skillsCompile(["--pack", "acme", "--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--json"]);

    const parsed = JSON.parse(logs.join("\n"));
    const watchCi = parsed.verbs.find((v: { name: string }) => v.name === "watch-ci");
    expect(watchCi.status).toBe("errored");
    expect(watchCi.files).toEqual([]);
    expect(watchCi.errors).toHaveLength(1);
    expect(watchCi.errors[0]).toContain("acme:helper-verb");

    const helper = parsed.verbs.find((v: { name: string }) => v.name === "helper-verb");
    expect(helper.status).toBe("internal-skipped");

    // An errored verb is a failed compile: the exit code says so, matching the
    // non-JSON throw and check --json's stale exit.
    expect(process.exitCode).toBe(1);
  });

  test("unbound required slot (compileVerb throws): errored, not a crash", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("acme", false);

    await skillsCompile(["--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--verb", "watch-ci", "--json"]);

    const parsed = JSON.parse(logs.join("\n"));
    expect(parsed.verbs).toHaveLength(1);
    expect(parsed.verbs[0].status).toBe("errored");
    expect(parsed.verbs[0].files).toEqual([]);
    expect(parsed.verbs[0].errors[0]).toContain("forge");
    expect(process.exitCode).toBe(1);
  });

  test("prints ONLY json -- no human lines on stdout", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("acme");

    await skillsCompile(["--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--verb", "watch-ci", "--json"]);

    expect(() => JSON.parse(logs.join("\n"))).not.toThrow();
  });
});

describe("skillsCompile --preview error handling", () => {
  test("lint-erroring verb: message on stderr, empty stdout, exit code set but no crash", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    writeFile(join(packDir, "pack", "stubs.jsonc"), STUBS_WITH_INTERNAL_REF);
    writeFile(join(packDir, "pack", "surface.jsonc"), `{ "public": ["watch-ci"] }\n`);
    const manifestPath = makeManifest("acme");

    const errors: string[] = [];
    const errorSpy = spyOn(console, "error").mockImplementation((...args: unknown[]) => {
      errors.push(args.map(String).join(" "));
    });
    try {
      await skillsCompile([
        "--pack", "acme", "--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath,
        "--verb", "watch-ci", "--preview",
      ]);
    } finally {
      errorSpy.mockRestore();
    }

    expect(logs).toEqual([]);
    expect(errors.join("\n")).toContain("acme:helper-verb");
    expect(process.exitCode).toBe(1);
  });

  test("erroring verb in a pack that ALSO has a misplaced compiled dir: still nothing on stdout", async () => {
    // Before the per-verb try/catch, an error always exited the whole command
    // immediately, so the post-loop "misplaced" scan (which prints to stdout)
    // was unreachable on any --preview error path. A bare `continue` in the
    // catch would let the loop end normally (--preview is single-verb) and
    // fall straight into that scan -- leaking a "misplaced: ..." line onto
    // stdout, breaking --preview's stdout-is-the-body-or-nothing contract.
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    writeFile(join(packDir, "pack", "stubs.jsonc"), STUBS_WITH_INTERNAL_REF);
    writeFile(join(packDir, "pack", "surface.jsonc"), `{ "public": ["watch-ci"] }\n`);
    writeFile(join(packDir, "skills", "leftover-verb", "SKILL.md"), "---\nname: leftover-verb\n---\nstale\n");
    const manifestPath = makeManifest("acme");

    const errors: string[] = [];
    const errorSpy = spyOn(console, "error").mockImplementation((...args: unknown[]) => {
      errors.push(args.map(String).join(" "));
    });
    try {
      await skillsCompile([
        "--pack", "acme", "--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath,
        "--verb", "watch-ci", "--preview",
      ]);
    } finally {
      errorSpy.mockRestore();
    }

    expect(logs).toEqual([]);
    expect(errors.join("\n")).toContain("acme:helper-verb");
  });

  test("unbound required slot: message on stderr, empty stdout, exit code set but no crash", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("acme", false);

    const errors: string[] = [];
    const errorSpy = spyOn(console, "error").mockImplementation((...args: unknown[]) => {
      errors.push(args.map(String).join(" "));
    });
    try {
      await skillsCompile([
        "--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath,
        "--verb", "watch-ci", "--preview",
      ]);
    } finally {
      errorSpy.mockRestore();
    }

    expect(logs).toEqual([]);
    expect(errors.join("\n")).toContain("forge");
    expect(process.exitCode).toBe(1);
  });
});

describe("skillsComposition --json", () => {
  test("verb, slots, fills, and binders reflect the manifest", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("acme");

    await skillsComposition(["--pack", "acme", "--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--json"]);

    const parsed = JSON.parse(logs.join("\n"));
    expect(parsed.pack).toBe("acme");
    expect(parsed.packDir).toBe(packDir);
    expect(parsed.verbs).toHaveLength(1);

    const verb = parsed.verbs[0];
    expect(verb.name).toBe("watch-ci");
    expect(verb.engine).toBe("watch-ci");
    expect(verb.engineRef).toBe("mattstack:watch-ci");
    expect(verb.plugin).toBe("mattstack");
    expect(verb.public).toBe(true);
    expect(verb.sourcePath).toBe(join(mattstackDir, "plugins", "mattstack", "skills", "pipeline", "watch-ci", "SKILL.md"));
    expect(verb.artifactPath).toBe(join(packDir, "skills", "watch-ci"));
    expect(verb.engineError).toBeUndefined();

    const domainSlot = verb.slots.find((s: { name: string }) => s.name === "domain");
    expect(domainSlot.contract).toBe("watch-ci-domain@1");
    expect(domainSlot.required).toBe(false);
    expect(domainSlot.boundTo).toBe("acme:watch-ci-domain");
    expect(domainSlot.fillSourcePath).toBe(
      join(mattstackDir, "plugins", "acme", "attachments", "watch-ci-domain", "SKILL.md"),
    );
    expect(domainSlot.fillVersion).toBe("0.3.0");
    expect(domainSlot.registered).toBe(false);
    expect(domainSlot.inlined).toBe(true);
    expect(domainSlot.resolveError).toBeUndefined();

    const forgeSlot = verb.slots.find((s: { name: string }) => s.name === "forge");
    expect(forgeSlot.required).toBe(true);
    expect(forgeSlot.boundTo).toBe("mattstack:gitlab-forge");
    expect(forgeSlot.registered).toBe(true);
    expect(forgeSlot.inlined).toBe(false);

    expect(parsed.fills).toHaveLength(2);
    const domainFill = parsed.fills.find((f: { binding: string }) => f.binding === "acme:watch-ci-domain");
    expect(domainFill).toEqual({
      binding: "acme:watch-ci-domain",
      provides: "watch-ci-domain@1",
      sourcePath: join(mattstackDir, "plugins", "acme", "attachments", "watch-ci-domain", "SKILL.md"),
      registered: false,
    });
    const forgeFill = parsed.fills.find((f: { binding: string }) => f.binding === "mattstack:gitlab-forge");
    expect(forgeFill.registered).toBe(true);
    expect(forgeFill.provides).toBe("ci-forge@1");

    const binder = parsed.binders.find((b: { ref: string }) => b.ref === "mattstack:watch-ci");
    expect(binder.verb).toBe("watch-ci");
    expect(binder.kind).toBe("verb");
    expect(binder.slots).toEqual([
      { name: "domain", boundTo: "acme:watch-ci-domain" },
      { name: "forge", boundTo: "mattstack:gitlab-forge" },
    ]);
  });

  test("degrades per-slot (dangling binding) and per-verb (broken engine) without blanking the payload", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    writeFile(join(packDir, "pack", "stubs.jsonc"), STUBS_TWO_VERBS);
    const manifestPath = makeManifestDanglingDomain();

    await skillsComposition(["--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--json"]);

    const parsed = JSON.parse(logs.join("\n"));
    expect(parsed.verbs).toHaveLength(2);

    const watchCi = parsed.verbs.find((v: { name: string }) => v.name === "watch-ci");
    expect(watchCi.engineRef).toBe("mattstack:watch-ci");
    expect(watchCi.engineError).toBeUndefined();
    const domainSlot = watchCi.slots.find((s: { name: string }) => s.name === "domain");
    expect(domainSlot.boundTo).toBe("acme:does-not-exist");
    expect(domainSlot.resolveError).toContain("does-not-exist");
    expect(domainSlot.fillSourcePath).toBeNull();
    expect(domainSlot.fillVersion).toBeNull();
    const forgeSlot = watchCi.slots.find((s: { name: string }) => s.name === "forge");
    expect(forgeSlot.resolveError).toBeUndefined();
    expect(forgeSlot.fillSourcePath).not.toBeNull();

    const broken = parsed.verbs.find((v: { name: string }) => v.name === "broken");
    expect(broken.engineRef).toBeNull();
    expect(broken.plugin).toBeNull();
    expect(broken.sourcePath).toBeNull();
    expect(broken.slots).toEqual([]);
    expect(broken.engineError).toContain("no-such-engine");
    expect(broken.artifactPath).toBe(join(packDir, "skills", "broken"));

    // The payload as a whole is still populated -- one broken verb/slot pair
    // does not blank fills or binders either.
    expect(parsed.fills.length).toBeGreaterThan(0);
    expect(parsed.binders.length).toBeGreaterThan(0);
  });

  test("ignores a stray --verb flag: verbs stays the full roster, never truncated", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    writeFile(join(packDir, "pack", "stubs.jsonc"), STUBS_TWO_VERBS);
    const manifestPath = makeManifest("acme");

    await skillsComposition([
      "--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath,
      "--verb", "watch-ci", "--json",
    ]);

    const parsed = JSON.parse(logs.join("\n"));
    expect(parsed.verbs.map((v: { name: string }) => v.name).sort()).toEqual(["broken", "watch-ci"]);
  });

  test("binder kind is derived from pipelines/roster membership, not a ref string heuristic", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestDir = realpathSync(mkdtempSync(join(tmpdir(), "rt-skills-cli-manifest-")));
    const manifestPath = join(manifestDir, "skills.jsonc");
    writeFile(manifestPath, `{
  "pipelines": {
    "feature": ["mattstack:stage-provision"]
  },
  "bindings": {
    "mattstack:watch-ci": {
      "domain": "acme:watch-ci-domain",
      "forge": "mattstack:gitlab-forge"
    },
    "mattstack:stage-provision": {
      "domain": "acme:watch-ci-domain"
    },
    "mattstack:review-core": {
      "criteria": "acme:watch-ci-domain"
    },
    "mr-board:review": {
      "skill": "acme:watch-ci-domain"
    }
  }
}
`);

    await skillsComposition(["--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--json"]);

    const parsed = JSON.parse(logs.join("\n"));
    const byRef = Object.fromEntries(parsed.binders.map((b: { ref: string; kind: string; verb: string | null }) => [b.ref, b]));

    // mattstack:stage-provision has NO roster verb, so this also proves kind
    // isn't derived by string-matching "stage-" -- only pipelines membership does it.
    expect(byRef["mattstack:watch-ci"]).toMatchObject({ kind: "verb", verb: "watch-ci" });
    expect(byRef["mattstack:stage-provision"]).toMatchObject({ kind: "stage", verb: null });
    expect(byRef["mattstack:review-core"]).toMatchObject({ kind: "skill", verb: null });
    expect(byRef["mr-board:review"]).toMatchObject({ kind: "external", verb: null });
  });

  test("rosterless pack: empty verbs, fills, and binders -- not a failure", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = realpathSync(mkdtempSync(join(tmpdir(), "rt-skills-cli-pack-empty-")));

    await skillsComposition(["--pack", "acme", "--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--json"]);

    const parsed = JSON.parse(logs.join("\n"));
    expect(parsed).toEqual({ pack: "acme", packDir, manifestPath: null, verbs: [], fills: [], binders: [], pipelines: {} });
  });

  test("manifestPath is the absolute manifest the bindings came from, not <packDir>/skills.jsonc", async () => {
    // The console names this path as the file to edit to rebind a slot. It is
    // NOT reconstructable from the pack name -- it lives in a registered repo
    // dir -- so the payload has to carry the real one or the console guesses.
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestDir = realpathSync(mkdtempSync(join(tmpdir(), "rt-skills-cli-manifest-path-")));
    const manifestPath = join(manifestDir, "skills.jsonc");
    writeFile(manifestPath, `{ "bindings": { "mattstack:watch-ci": { "domain": "acme:watch-ci-domain" } } }`);

    await skillsComposition(["--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--json"]);

    const parsed = JSON.parse(logs.join("\n"));
    expect(parsed.manifestPath).toBe(manifestPath);
    expect(parsed.manifestPath).not.toBe(join(packDir, "skills.jsonc"));
  });

  test("pipelines carries each work type's stage order, not a set", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestDir = realpathSync(mkdtempSync(join(tmpdir(), "rt-skills-cli-manifest-order-")));
    const manifestPath = join(manifestDir, "skills.jsonc");
    // Deliberately NOT alphabetical: ship precedes provision. Anything that
    // rebuilt this list from binders[] or routed it through a Set would come
    // back sorted or in binding-insertion order, and a consumer rendering
    // execution order would show the pipeline running backwards with nothing
    // failing anywhere.
    writeFile(manifestPath, `{
  "pipelines": {
    "feature": ["mattstack:stage-ship", "mattstack:stage-provision", "mattstack:stage-plan"],
    "bugfix": ["mattstack:stage-provision"]
  },
  "bindings": {
    "mattstack:watch-ci": {
      "domain": "acme:watch-ci-domain"
    }
  }
}
`);

    await skillsComposition(["--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--json"]);

    const parsed = JSON.parse(logs.join("\n"));
    expect(parsed.pipelines).toEqual({
      feature: ["mattstack:stage-ship", "mattstack:stage-provision", "mattstack:stage-plan"],
      bugfix: ["mattstack:stage-provision"],
    });
  });

  test("prints ONLY json -- no human lines on stdout", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("acme");

    await skillsComposition(["--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--json"]);

    expect(() => JSON.parse(logs.join("\n"))).not.toThrow();
  });
});

describe("skillsPacks --json", () => {
  test("no packs discovered: empty packs array, not an error", async () => {
    await skillsPacks(["--settings-path", "/nonexistent/settings.json", "--json"]);

    const parsed = JSON.parse(logs.join("\n"));
    expect(parsed).toEqual({ packs: [] });
  });

  test("prints ONLY json -- no human lines on stdout", async () => {
    await skillsPacks(["--settings-path", "/nonexistent/settings.json", "--json"]);

    expect(() => JSON.parse(logs.join("\n"))).not.toThrow();
  });
});
