import { afterEach, beforeEach, describe, expect, spyOn, test } from "bun:test";
import { execFileSync } from "child_process";
import { chmodSync, cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, realpathSync, rmSync, statSync, symlinkSync, writeFileSync } from "fs";
import { tmpdir } from "os";
import { dirname, join } from "path";
import { skillsCheck, skillsCompile, skillsComposition, skillsPacks } from "../skills.ts";
import { compileSkill } from "../../lib/skills/compile.ts";
import { invocableRoster, loadAttachment, loadStepSource } from "../../lib/skills/sources.ts";
import type { PluginRoots } from "../../lib/skills/sources.ts";
import type { VerbDef } from "../../lib/skills/types.ts";
import { runExpectingCleanExit } from "../../lib/skills/__tests__/helpers.ts";

function writeFile(path: string, content: string): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content);
}

const WATCH_CI_SKILL_MD = `---
name: watch-ci
description: "Watch CI until it goes green"
type: pipeline-step
allowed-tools:
  - "Bash(gh:*)"
  - "Read"
slots:
  domain: { contract: "watch-ci-domain@1" }
  forge: { contract: "ci-forge@1", required: true }
---

Poll the pipeline every 30s and report status. See \${CLAUDE_SKILL_DIR}/scripts/ci-watch.sh for the poller.
`;

const WATCH_CI_SCRIPT = "#!/bin/sh\necho polling\n";

const DOMAIN_SKILL_MD = `---
name: watch-ci-domain
description: "Domain rules for watch-ci"
metadata:
  provides: "watch-ci-domain@1"
allowed-tools:
  - "Read(\${CLAUDE_SKILL_DIR}/ci-config.json)"
---

Domain rules live at \${CLAUDE_SKILL_DIR}/ci-config.json for details.
`;

const CI_CONFIG_JSON = `{ "noisy": ["flaky-job"] }\n`;

const FORGE_SKILL_MD = `---
name: gitlab-forge
description: "Talk to GitLab via glab"
metadata:
  provides: "ci-forge@1"
allowed-tools:
  - "Bash(glab:*)"
---

Talk to GitLab via glab.
`;

const STUBS_JSONC = `{
  "verbs": {
    "watch-ci": {
      "engine": "watch-ci",
      "description": "Use when watching or triaging CI."
    }
  }
}
`;

/**
 * A second, unrelated verb ("helper-verb") sharing watch-ci's engine, kept
 * out of surface.jsonc's public list so computeInternalRoster tags it
 * "acme:helper-verb" -- watch-ci's own description names that token,
 * which is exactly what lintInternalRoster flags (the only producer of
 * compileVerb's returned errors[], as opposed to a thrown failure).
 */
const STUBS_WITH_INTERNAL_REF = `{
  "verbs": {
    "watch-ci": {
      "engine": "watch-ci",
      "description": "Use when watching CI; see acme:helper-verb for internal detail."
    },
    "helper-verb": {
      "engine": "watch-ci",
      "description": "Internal helper, never surfaced."
    }
  }
}
`;

/** One compilable verb ahead of two that name engines no plugin root carries -- the ordering that used to emit watch-ci before the first throw. */
const STUBS_ONE_GOOD_TWO_BROKEN = `{
  "verbs": {
    "watch-ci": {
      "engine": "watch-ci",
      "description": "Use when watching or triaging CI."
    },
    "broken-a": {
      "engine": "no-such-engine-a",
      "description": "Points at a retired engine."
    },
    "broken-b": {
      "engine": "no-such-engine-b",
      "description": "Points at another retired engine."
    }
  }
}
`;

/** A second verb pointing at an engine that does not exist under any plugin root -- loadStepSource throws. */
const STUBS_TWO_VERBS = `{
  "verbs": {
    "watch-ci": {
      "engine": "watch-ci",
      "description": "Use when watching or triaging CI."
    },
    "broken": {
      "engine": "no-such-engine",
      "description": "Points at a retired engine."
    }
  }
}
`;

function manifestJsonc(team: string, withForge: boolean): string {
  const bindings = withForge
    ? `{
      "domain": "acme:watch-ci-domain",
      "forge": "mattstack:gitlab-forge"
    }`
    : `{
      "domain": "acme:watch-ci-domain"
    }`;
  return `// GENERATED by merge-manifests.sh -- do not hand-edit;
// provenance (binding <- source):
//   mattstack:watch-ci domain <- ${team}@${team}
{
  "bindings": {
    "mattstack:watch-ci": ${bindings}
  }
}
`;
}

/** A trivial, no-slot stage step -- resolve() now builds StageEntry[] for every pipeline name a test manifest declares, so any such name needs a real SKILL.md behind it. */
function stageSkillMd(name: string, stage: string): string {
  return `---
name: ${name}
description: "${stage} stage"
type: pipeline-step
metadata:
  stage: ${stage}
---

${stage}.
`;
}

/**
 * Fixture "mattstack home" root: plugins/<name>/ mirrors resolvePluginRoots()'s
 * real shape (dir + .claude-plugin/plugin.json) so skillsCompile's test-mode
 * root resolution and the golden compile below walk identical trees.
 */
function makeMattstackDir(): string {
  const dir = realpathSync(mkdtempSync(join(tmpdir(), "rt-skills-cli-mattstack-")));

  const mattstackPluginDir = join(dir, "plugins", "mattstack");
  writeFile(join(mattstackPluginDir, ".claude-plugin", "plugin.json"), JSON.stringify({ version: "1.2.0" }));
  writeFile(join(mattstackPluginDir, "skills", "pipeline", "watch-ci", "SKILL.md"), WATCH_CI_SKILL_MD);
  writeFile(join(mattstackPluginDir, "skills", "pipeline", "watch-ci", "scripts", "ci-watch.sh"), WATCH_CI_SCRIPT);
  chmodSync(join(mattstackPluginDir, "skills", "pipeline", "watch-ci", "scripts", "ci-watch.sh"), 0o755);
  writeFile(join(mattstackPluginDir, "skills", "gitlab-forge", "SKILL.md"), FORGE_SKILL_MD);
  writeFile(join(mattstackPluginDir, "attachments", "pipeline", "stage-plan", "SKILL.md"), stageSkillMd("stage-plan", "plan"));
  writeFile(join(mattstackPluginDir, "attachments", "pipeline", "stage-provision", "SKILL.md"), stageSkillMd("stage-provision", "provision"));
  writeFile(join(mattstackPluginDir, "attachments", "pipeline", "stage-ship", "SKILL.md"), stageSkillMd("stage-ship", "ship"));

  const acmePluginDir = join(dir, "plugins", "acme");
  writeFile(join(acmePluginDir, ".claude-plugin", "plugin.json"), JSON.stringify({ version: "0.3.0" }));
  writeFile(join(acmePluginDir, "attachments", "watch-ci-domain", "SKILL.md"), DOMAIN_SKILL_MD);
  writeFile(join(acmePluginDir, "attachments", "watch-ci-domain", "ci-config.json"), CI_CONFIG_JSON);

  return dir;
}

function makePackDir(): string {
  const dir = realpathSync(mkdtempSync(join(tmpdir(), "rt-skills-cli-pack-")));
  writeFile(join(dir, "pack", "stubs.jsonc"), STUBS_JSONC);
  return dir;
}

function makeManifest(team: string, withForge = true): string {
  const dir = realpathSync(mkdtempSync(join(tmpdir(), "rt-skills-cli-manifest-")));
  const path = join(dir, "skills.jsonc");
  writeFile(path, manifestJsonc(team, withForge));
  return path;
}

/** domain is bound to a name nothing provides -- loadAttachment throws, exercising composition's per-slot degrade. */
function makeManifestDanglingDomain(): string {
  const dir = realpathSync(mkdtempSync(join(tmpdir(), "rt-skills-cli-manifest-")));
  const path = join(dir, "skills.jsonc");
  writeFile(path, `{
  "bindings": {
    "mattstack:watch-ci": {
      "domain": "acme:does-not-exist",
      "forge": "mattstack:gitlab-forge"
    }
  }
}
`);
  return path;
}

function computeGolden(mattstackDir: string) {
  const roots: PluginRoots = {
    byName: {
      mattstack: { dir: join(mattstackDir, "plugins", "mattstack"), version: "1.2.0" },
      acme: { dir: join(mattstackDir, "plugins", "acme"), version: "0.3.0" },
    },
  };
  const verb: VerbDef = { name: "watch-ci", engine: "watch-ci", description: "Use when watching or triaging CI." };
  const step = loadStepSource("watch-ci", roots);
  const domain = loadAttachment("acme:watch-ci-domain", "domain", roots);
  const forge = loadAttachment("mattstack:gitlab-forge", "forge", roots);
  const invocable = invocableRoster(roots);
  return compileSkill(verb, step, { domain, forge }, invocable);
}

let logSpy: ReturnType<typeof spyOn>;
let logs: string[];

beforeEach(() => {
  logs = [];
  logSpy = spyOn(console, "log").mockImplementation((...args: unknown[]) => {
    logs.push(args.map(String).join(" "));
  });
});

afterEach(() => {
  logSpy.mockRestore();
  // skillsCheck sets this on staleness; Bun ignores process.exitCode = undefined once
  // truthy, so 0 is the only value that clears it before the suite's own exit status.
  process.exitCode = 0;
});

describe("skillsCompile", () => {
  test("dry-run prints a would-write summary and writes nothing", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("t");

    await skillsCompile([
      "--team", "t",
      "--dry-run",
      "--pack-dir", packDir,
      "--mattstack-dir", mattstackDir,
      "--manifest", manifestPath,
      "--verb", "watch-ci",
    ]);

    const summary = logs.find((l) => /would write \d+ files/.test(l));
    expect(summary).toBeDefined();
    expect(summary).toContain("watch-ci");
    expect(existsSync(join(packDir, "skills", "watch-ci"))).toBe(false);
  });

  test("--preview prints the compiled body and writes nothing", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("t");

    await skillsCompile(["--pack", "t", "--verb", "watch-ci", "--preview",
      "--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath]);

    const out = logs.join("\n");
    expect(out).toContain("<!-- part: step source=");
    expect(out).not.toContain("compiled watch-ci (");
    expect(existsSync(join(packDir, "skills", "watch-ci"))).toBe(false);
  });

  test("--preview requires exactly one verb", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("t");

    const { exitCode, errors } = await runExpectingCleanExit(() =>
      skillsCompile(["--pack", "t", "--preview",
        "--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath]));

    expect(exitCode).toBe(1);
    expect(errors.join("\n")).toContain("--preview needs a single --verb");
  });

  test("--preview on a retired (surface-internal) verb leaves its stale output directory alone", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("t");
    // watch-ci is absent from surface.jsonc's public list, so it is internal/retired --
    // this is the transition-window state computeInternalRoster's own comment describes.
    writeFile(join(packDir, "pack", "surface.jsonc"), `{ "public": [] }\n`);
    // A stale output dir from an earlier (pre-retirement) real compile.
    writeFile(join(packDir, "skills", "watch-ci", "SKILL.md"), "stale\n");

    await skillsCompile(["--pack", "t", "--verb", "watch-ci", "--preview",
      "--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath]);

    expect(existsSync(join(packDir, "skills", "watch-ci"))).toBe(true);
  });

  test("--preview on a non-public verb still previews the compiled body, writing nothing to disk", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("t");
    writeFile(join(packDir, "pack", "surface.jsonc"), `{ "public": [] }\n`);

    await skillsCompile(["--pack", "t", "--verb", "watch-ci", "--preview",
      "--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath]);

    const out = logs.join("\n");
    expect(out).toContain("<!-- part: step source=");
    expect(existsSync(join(packDir, "skills", "watch-ci"))).toBe(false);
    expect(existsSync(join(packDir, "attachments", "watch-ci"))).toBe(false);
  });

  test("non-public verb previewed alongside a misplaced compiled dir elsewhere: still nothing but the body on stdout", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("t");
    writeFile(join(packDir, "pack", "surface.jsonc"), `{ "public": [] }\n`);
    // Registered on disk, absent from the public list, and NOT the requested
    // verb: exactly what the post-loop "misplaced" scan reports -- but that
    // scan never runs under --preview, so it must not leak onto stdout here.
    writeFile(join(packDir, "skills", "stray-skill", "SKILL.md"), "# stray\n");

    await skillsCompile(["--pack", "t", "--verb", "watch-ci", "--preview",
      "--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath]);

    const out = logs.join("\n");
    expect(out).toContain("<!-- part: step source=");
    expect(out).not.toContain("misplaced:");
  });

  test("real run emits SKILL.md + vendored files matching a golden compile, byte for byte", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("t");

    await skillsCompile([
      "--team", "t",
      "--pack-dir", packDir,
      "--mattstack-dir", mattstackDir,
      "--manifest", manifestPath,
      "--verb", "watch-ci",
    ]);

    expect(logs.some((l) => l.includes("compiled watch-ci") && l.includes("3 files"))).toBe(true);

    const golden = computeGolden(mattstackDir);
    const outDir = join(packDir, "skills", "watch-ci");

    for (const file of golden.files) {
      const dest = join(outDir, file.path);
      expect(existsSync(dest)).toBe(true);
      const expected = "content" in file ? file.content : readFileSync(file.copyFrom, "utf8");
      expect(readFileSync(dest, "utf8")).toBe(expected);
    }

    const scriptPath = join(outDir, "scripts", "ci-watch.sh");
    expect(statSync(scriptPath).mode & 0o111).not.toBe(0);
  });

  test("missing required binding: clean one-line error naming verb and slot, exit 1, no partial write", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("t", false);

    const { exitCode, errors } = await runExpectingCleanExit(() =>
      skillsCompile([
        "--team", "t",
        "--pack-dir", packDir,
        "--mattstack-dir", mattstackDir,
        "--manifest", manifestPath,
        "--verb", "watch-ci",
      ]),
    );

    expect(exitCode).toBe(1);
    expect(errors).toHaveLength(1);
    expect(errors[0]).toStartWith("rt skills: ");
    expect(errors[0]).not.toContain("\n    at "); // no stack trace
    expect(errors[0]).toContain("watch-ci");
    expect(errors[0]).toContain("forge");
    expect(existsSync(join(packDir, "skills", "watch-ci"))).toBe(false);
  });

  test("one errored verb aborts the whole compile: every error reported, nothing written", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("t");
    writeFile(join(packDir, "pack", "stubs.jsonc"), STUBS_ONE_GOOD_TWO_BROKEN);
    // A previous compile's output for the one verb that DOES compile: surviving
    // byte for byte is what proves the failing run never reached the disk.
    writeFile(join(packDir, "skills", "watch-ci", "SKILL.md"), "PLANTED\n");

    const { exitCode, errors } = await runExpectingCleanExit(() =>
      skillsCompile([
        "--team", "t",
        "--pack-dir", packDir,
        "--mattstack-dir", mattstackDir,
        "--manifest", manifestPath,
      ]),
    );

    expect(exitCode).toBe(1);
    expect(errors).toHaveLength(2);
    expect(errors.every((e) => e.startsWith("rt skills: "))).toBe(true);
    expect(errors.join("\n")).toContain("no-such-engine-a");
    expect(errors.join("\n")).toContain("no-such-engine-b");
    expect(readFileSync(join(packDir, "skills", "watch-ci", "SKILL.md"), "utf8")).toBe("PLANTED\n");
  });

  test("an engine body reading outside the pack root: clean one-line error, exit 1, nothing written", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("t");
    writeFile(
      join(mattstackDir, "plugins", "mattstack", "skills", "pipeline", "watch-ci", "SKILL.md"),
      WATCH_CI_SKILL_MD.replace(
        "Poll the pipeline every 30s",
        "Read `../../../elsewhere/SKILL.md` first. Poll the pipeline every 30s",
      ),
    );

    const { exitCode, errors } = await runExpectingCleanExit(() =>
      skillsCompile([
        "--team", "t",
        "--pack-dir", packDir,
        "--mattstack-dir", mattstackDir,
        "--manifest", manifestPath,
        "--verb", "watch-ci",
      ]),
    );

    expect(exitCode).toBe(1);
    expect(errors.join("\n")).toContain("../../../elsewhere/SKILL.md");
    // The engine's own file and line, not a coordinate in an artifact this run
    // refuses to write.
    expect(errors.join("\n")).toContain("at skills/pipeline/watch-ci/SKILL.md:13 resolves outside the pack root");
    expect(existsSync(join(packDir, "skills", "watch-ci"))).toBe(false);
  });

  test("unrecognized argument: clean one-line error, exit 1", async () => {
    const { exitCode, errors } = await runExpectingCleanExit(() =>
      skillsCompile(["--bogus-flag"]),
    );

    expect(exitCode).toBe(1);
    expect(errors).toHaveLength(1);
    expect(errors[0]).toStartWith("rt skills: ");
    expect(errors[0]).toContain("--bogus-flag");
  });

  test("unknown verb: clean one-line error, exit 1", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("t");

    const { exitCode, errors } = await runExpectingCleanExit(() =>
      skillsCompile([
        "--team", "t",
        "--pack-dir", packDir,
        "--mattstack-dir", mattstackDir,
        "--manifest", manifestPath,
        "--verb", "no-such-verb",
      ]),
    );

    expect(exitCode).toBe(1);
    expect(errors).toHaveLength(1);
    expect(errors[0]).toStartWith("rt skills: ");
    expect(errors[0]).toContain("no-such-verb");
  });

  test("absent manifest (no skills.jsonc names the team): clean one-line error, exit 1", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();

    const { exitCode, errors } = await runExpectingCleanExit(() =>
      skillsCompile([
        "--team", "t",
        "--pack-dir", packDir,
        "--mattstack-dir", mattstackDir,
        "--verb", "watch-ci",
      ]),
    );

    expect(exitCode).toBe(1);
    expect(errors).toHaveLength(1);
    expect(errors[0]).toStartWith("rt skills: ");
    expect(errors[0]).toContain("skills.jsonc");
  });

  test("a symlinked plugin dir under --mattstack-dir resolves as a plugin root", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("t");
    const linkedAcme = realpathSync(mkdtempSync(join(tmpdir(), "rt-skills-cli-acme-")));
    cpSync(join(mattstackDir, "plugins", "acme"), linkedAcme, { recursive: true });
    rmSync(join(mattstackDir, "plugins", "acme"), { recursive: true, force: true });
    symlinkSync(linkedAcme, join(mattstackDir, "plugins", "acme"));

    const { exitCode, errors } = await runExpectingCleanExit(() =>
      skillsCompile([
        "--team", "t",
        "--dry-run",
        "--pack-dir", packDir,
        "--mattstack-dir", mattstackDir,
        "--manifest", manifestPath,
        "--verb", "watch-ci",
      ]),
    );

    expect(errors).toEqual([]);
    expect(exitCode).toBeUndefined();
    expect(logs.some((l) => /would write \d+ files/.test(l))).toBe(true);
  });

  test("default pack dir formula (--team + --mattstack-dir, no --pack-dir)", async () => {
    const mattstackDir = makeMattstackDir();
    const manifestPath = makeManifest("t");
    writeFile(join(mattstackDir, "teams", "t", "mattstack", "packs", "t", "pack", "stubs.jsonc"), STUBS_JSONC);

    await skillsCompile([
      "--team", "t",
      "--dry-run",
      "--mattstack-dir", mattstackDir,
      "--manifest", manifestPath,
    ]);

    expect(logs.some((l) => /would write \d+ files/.test(l) && l.includes("watch-ci"))).toBe(true);
  });

  test("default manifest lookup (--mattstack-dir only, no --manifest)", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    writeFile(join(mattstackDir, "repos", "some-repo", "skills.jsonc"), manifestJsonc("t", true));

    await skillsCompile([
      "--team", "t",
      "--dry-run",
      "--pack-dir", packDir,
      "--mattstack-dir", mattstackDir,
      "--verb", "watch-ci",
    ]);

    expect(logs.some((l) => /would write \d+ files/.test(l))).toBe(true);
  });

  test("default manifest lookup matches the provenance source (<- team@), not a binding key that merely mentions the team", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    writeFile(join(mattstackDir, "repos", "some-repo", "skills.jsonc"), `// GENERATED by merge-manifests.sh -- do not hand-edit;
// provenance (binding <- source):
//   mattstack:watch-ci domain <- acme@acme
{
  "bindings": {
    "mattstack:watch-ci": { "domain": "acme:watch-ci-domain", "forge": "mattstack:gitlab-forge" }
  }
}
`);

    const { exitCode, errors } = await runExpectingCleanExit(() =>
      skillsCompile([
        "--team", "mattstack",
        "--dry-run",
        "--pack-dir", packDir,
        "--mattstack-dir", mattstackDir,
        "--verb", "watch-ci",
      ]),
    );

    expect(exitCode).toBe(1);
    expect(errors).toHaveLength(1);
    expect(errors[0]).toContain('names team "mattstack"');
  });

  test("a standalone pack (outside the teams zone) with no registered manifest compiles against its own pack/skills.jsonc", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    writeFile(join(packDir, "pack", "skills.jsonc"), manifestJsonc("t", true));

    const { exitCode, errors } = await runExpectingCleanExit(() =>
      skillsCompile([
        "--team", "t",
        "--dry-run",
        "--pack-dir", packDir,
        "--mattstack-dir", mattstackDir,
        "--verb", "watch-ci",
      ]),
    );

    expect(errors).toEqual([]);
    expect(exitCode).toBeUndefined();
    expect(logs.some((l) => /would write \d+ files/.test(l) && l.includes("watch-ci"))).toBe(true);
  });

  test("a team-zone pack never falls back to its own pack/skills.jsonc: that file is a fragment, not the repo's manifest", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = join(mattstackDir, "teams", "t", "mattstack", "packs", "t");
    writeFile(join(packDir, "pack", "stubs.jsonc"), STUBS_JSONC);
    writeFile(join(packDir, "pack", "skills.jsonc"), manifestJsonc("t", true));

    const { exitCode, errors } = await runExpectingCleanExit(() =>
      skillsCompile([
        "--team", "t",
        "--dry-run",
        "--mattstack-dir", mattstackDir,
        "--verb", "watch-ci",
      ]),
    );

    expect(exitCode).toBe(1);
    expect(errors).toHaveLength(1);
    expect(errors[0]).toContain("skills.jsonc");
  });
});

describe("skillsCompile --json write semantics", () => {
  test("--json --dry-run reports the plan, written false, and touches nothing", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("t");

    await skillsCompile([
      "--team", "t",
      "--json",
      "--dry-run",
      "--pack-dir", packDir,
      "--mattstack-dir", mattstackDir,
      "--manifest", manifestPath,
      "--verb", "watch-ci",
    ]);

    const payload = JSON.parse(logs[0]!);
    expect(payload.written).toBe(false);
    expect(payload.verbs[0].status).toBe("compiled");
    expect(existsSync(join(packDir, "skills", "watch-ci"))).toBe(false);
  });

  test("--json with an errored verb writes nothing, reports every row, exits 1", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    writeFile(join(packDir, "pack", "stubs.jsonc"), STUBS_ONE_GOOD_TWO_BROKEN);
    const manifestPath = makeManifest("t");

    await skillsCompile([
      "--team", "t",
      "--json",
      "--pack-dir", packDir,
      "--mattstack-dir", mattstackDir,
      "--manifest", manifestPath,
    ]);

    expect(process.exitCode).toBe(1);
    const payload = JSON.parse(logs[0]!);
    expect(payload.written).toBe(false);
    const statuses = Object.fromEntries(payload.verbs.map((v: { name: string; status: string }) => [v.name, v.status]));
    expect(statuses["watch-ci"]).toBe("compiled");
    expect(statuses["broken-a"]).toBe("errored");
    expect(statuses["broken-b"]).toBe("errored");
    expect(existsSync(join(packDir, "skills", "watch-ci"))).toBe(false);
  });

  test("--preview with --json is a usage error, not a silent report", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("t");

    const { exitCode, errors } = await runExpectingCleanExit(() =>
      skillsCompile(["--pack", "t", "--verb", "watch-ci", "--preview", "--json",
        "--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath]));

    expect(exitCode).toBe(1);
    expect(errors.join("\n")).toContain("--preview");
  });

  test("--json reports misplaced skills in the payload, not as stray stdout lines", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("t");
    writeFile(join(packDir, "pack", "surface.jsonc"), `{ "public": ["watch-ci"] }\n`);
    writeFile(join(packDir, "skills", "stray-skill", "SKILL.md"), "# stray\n");

    await skillsCompile([
      "--team", "t",
      "--json",
      "--pack-dir", packDir,
      "--mattstack-dir", mattstackDir,
      "--manifest", manifestPath,
      "--verb", "watch-ci",
    ]);

    expect(logs).toHaveLength(1);
    const payload = JSON.parse(logs[0]!);
    expect(payload.misplaced).toEqual(["stray-skill"]);
    expect(process.exitCode).toBe(1);
  });
});

describe("skillsCompile pack resolution from cwd", () => {
  test("cwd inside a pack dir resolves that pack when no --pack/--pack-dir is given", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    writeFile(join(packDir, "pack", "surface.jsonc"), `{ "public": ["watch-ci"] }\n`);
    const manifestPath = makeManifest("t");

    const prevCwd = process.cwd();
    process.chdir(packDir);
    try {
      const { exitCode, errors } = await runExpectingCleanExit(() =>
        skillsCompile(["--dry-run", "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--verb", "watch-ci"]));
      expect(errors).toEqual([]);
      expect(exitCode).toBeUndefined();
    } finally {
      process.chdir(prevCwd);
    }

    expect(logs.some((l) => /would write \d+ files/.test(l) && l.includes("watch-ci"))).toBe(true);
  });

  test("cwd below the pack root still resolves the enclosing pack", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    writeFile(join(packDir, "pack", "surface.jsonc"), `{ "public": ["watch-ci"] }\n`);
    const manifestPath = makeManifest("t");

    const prevCwd = process.cwd();
    process.chdir(join(packDir, "pack"));
    try {
      const { exitCode, errors } = await runExpectingCleanExit(() =>
        skillsCompile(["--dry-run", "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--verb", "watch-ci"]));
      expect(errors).toEqual([]);
      expect(exitCode).toBeUndefined();
    } finally {
      process.chdir(prevCwd);
    }

    expect(logs.some((l) => /would write \d+ files/.test(l) && l.includes("watch-ci"))).toBe(true);
  });

  test("--pack matching the enclosing pack's plugin name resolves to the enclosing dir, not the registry", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    writeFile(join(packDir, "pack", "surface.jsonc"), `{ "public": ["watch-ci"] }\n`);
    writeFile(join(packDir, ".claude-plugin", "plugin.json"), JSON.stringify({ name: "t", version: "0.0.1" }));
    const manifestPath = makeManifest("t");

    const prevCwd = process.cwd();
    process.chdir(packDir);
    try {
      const { exitCode, errors } = await runExpectingCleanExit(() =>
        skillsCompile(["--pack", "t", "--dry-run", "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--verb", "watch-ci"]));
      expect(errors).toEqual([]);
      expect(exitCode).toBeUndefined();
    } finally {
      process.chdir(prevCwd);
    }

    expect(logs.some((l) => /would write \d+ files/.test(l) && l.includes("watch-ci"))).toBe(true);
  });

  test("--pack naming a different pack does not hijack onto the enclosing dir", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    writeFile(join(packDir, "pack", "surface.jsonc"), `{ "public": ["watch-ci"] }\n`);
    const manifestPath = makeManifest("t");

    const prevCwd = process.cwd();
    process.chdir(packDir);
    try {
      const { exitCode, errors } = await runExpectingCleanExit(() =>
        skillsCompile(["--pack", "other", "--dry-run", "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--verb", "watch-ci"]));
      expect(exitCode).toBe(1);
      expect(errors.join("\n")).toContain(`no pack named "other"`);
    } finally {
      process.chdir(prevCwd);
    }
  });
});

/**
 * A "work" orchestrator (places {{pipeline.stages}}) plus one stage
 * (metadata.stage: plan) declared via the manifest's pipelines map -- the
 * minimal fixture for exercising --verb scoping across the roster-verb and
 * pipeline-stage name spaces together.
 */
function makePipelineFixtures(): { mattstackDir: string; packDir: string; manifestPath: string } {
  const mattstackDir = realpathSync(mkdtempSync(join(tmpdir(), "rt-skills-cli-pipeline-mattstack-")));
  const mattstackPluginDir = join(mattstackDir, "plugins", "mattstack");
  writeFile(join(mattstackPluginDir, ".claude-plugin", "plugin.json"), JSON.stringify({ version: "1.0.0" }));
  writeFile(
    join(mattstackPluginDir, "attachments", "pipeline", "work", "SKILL.md"),
    `---\nname: work\ndescription: "Run the work pipeline"\ntype: pipeline-step\n---\n\n{{work-type}}\n{{pipeline.stages}}\n`,
  );
  writeFile(join(mattstackPluginDir, "attachments", "pipeline", "stage-plan", "SKILL.md"), stageSkillMd("stage-plan", "plan"));

  const packDir = realpathSync(mkdtempSync(join(tmpdir(), "rt-skills-cli-pipeline-pack-")));
  writeFile(join(packDir, "pack", "stubs.jsonc"), `{ "verbs": { "work": { "engine": "work", "description": "Run the pipeline." } } }\n`);
  writeFile(join(packDir, "pack", "surface.jsonc"), JSON.stringify({ public: ["work"] }));

  const manifestDir = realpathSync(mkdtempSync(join(tmpdir(), "rt-skills-cli-pipeline-manifest-")));
  const manifestPath = join(manifestDir, "skills.jsonc");
  writeFile(manifestPath, `{\n  "pipelines": { "feature": ["mattstack:stage-plan"] },\n  "bindings": {}\n}\n`);

  return { mattstackDir, packDir, manifestPath };
}

describe("skillsCompile/skillsCheck --verb scoping across roster verbs and pipeline stages", () => {
  test("--verb work --preview emits exactly the orchestrator's body, not every stage's too", async () => {
    const { mattstackDir, packDir, manifestPath } = makePipelineFixtures();

    await skillsCompile([
      "--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath,
      "--verb", "work", "--preview",
    ]);

    // Strict, not toContain: a stray second console.log (the stage's body
    // concatenated after the orchestrator's) is exactly the N+1-bodies bug --
    // toContain would have passed with two bodies on stdout.
    expect(logs).toHaveLength(1);
    expect(logs[0]).toContain("The work type is `feature`. Continue.");
  });

  test("--verb stage-plan --preview emits exactly that stage's body, not the orchestrator's", async () => {
    const { mattstackDir, packDir, manifestPath } = makePipelineFixtures();

    await skillsCompile([
      "--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath,
      "--verb", "stage-plan", "--preview",
    ]);

    expect(logs).toHaveLength(1);
    expect(logs[0]).not.toContain("The work type is");
  });

  test("--verb work (real compile) writes only the orchestrator, leaving the stage uncompiled", async () => {
    const { mattstackDir, packDir, manifestPath } = makePipelineFixtures();

    await skillsCompile([
      "--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--verb", "work",
    ]);

    expect(existsSync(join(packDir, "skills", "work", "SKILL.md"))).toBe(true);
    expect(existsSync(join(packDir, "attachments", "stage-plan"))).toBe(false);
  });

  test("skillsCheck --verb stage-plan --json reports only that stage, not the orchestrator", async () => {
    const { mattstackDir, packDir, manifestPath } = makePipelineFixtures();

    await skillsCheck([
      "--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath,
      "--verb", "stage-plan", "--json",
    ]);

    const parsed = JSON.parse(logs.join("\n"));
    expect(parsed.verbs.map((v: { name: string }) => v.name)).toEqual(["stage-plan"]);
  });

  test("an unknown --verb naming neither a roster verb nor a pipeline stage: clean one-line error", async () => {
    const { mattstackDir, packDir, manifestPath } = makePipelineFixtures();

    const { exitCode, errors } = await runExpectingCleanExit(() =>
      skillsCompile([
        "--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--verb", "no-such-name",
      ]),
    );

    expect(exitCode).toBe(1);
    expect(errors).toHaveLength(1);
    expect(errors[0]).toStartWith("rt skills: ");
    expect(errors[0]).toContain("no-such-name");
  });
});

describe("skillsCompile with a broken pipeline manifest", () => {
  test("a pipeline naming a stage with no backing SKILL.md fails cleanly, not with a stack trace", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestDir = realpathSync(mkdtempSync(join(tmpdir(), "rt-skills-cli-manifest-bad-pipeline-")));
    const manifestPath = join(manifestDir, "skills.jsonc");
    writeFile(manifestPath, `{\n  "pipelines": { "feature": ["mattstack:no-such-stage"] },\n  "bindings": {}\n}\n`);

    const { exitCode, errors } = await runExpectingCleanExit(() =>
      skillsCompile([
        "--team", "t",
        "--pack-dir", packDir,
        "--mattstack-dir", mattstackDir,
        "--manifest", manifestPath,
      ]),
    );

    expect(exitCode).toBe(1);
    expect(errors).toHaveLength(1);
    expect(errors[0]).toStartWith("rt skills: ");
    expect(errors[0]).not.toContain("\n    at ");
    expect(errors[0]).toContain("feature");
    expect(errors[0]).toContain("no-such-stage");
  });

  test("a name that is both a roster verb and a pipeline stage errors instead of silently deleting its own output", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    writeFile(
      join(packDir, "pack", "stubs.jsonc"),
      `{\n  "verbs": {\n    "watch-ci": { "engine": "watch-ci", "description": "Watch CI." },\n    "stage-plan": { "engine": "stage-plan", "description": "Also a roster verb, oops." }\n  }\n}\n`,
    );
    const manifestDir = realpathSync(mkdtempSync(join(tmpdir(), "rt-skills-cli-manifest-collision-")));
    const manifestPath = join(manifestDir, "skills.jsonc");
    writeFile(manifestPath, `{\n  "pipelines": { "feature": ["mattstack:stage-plan"] },\n  "bindings": {}\n}\n`);

    const { exitCode, errors } = await runExpectingCleanExit(() =>
      skillsCompile([
        "--team", "t",
        "--pack-dir", packDir,
        "--mattstack-dir", mattstackDir,
        "--manifest", manifestPath,
      ]),
    );

    expect(exitCode).toBe(1);
    expect(errors).toHaveLength(1);
    expect(errors[0]).toStartWith("rt skills: ");
    expect(errors[0]).toContain("stage-plan");
    expect(errors[0]).toContain("both a roster verb and a pipeline stage");
    expect(existsSync(join(packDir, "skills", "stage-plan"))).toBe(false);
    expect(existsSync(join(packDir, "attachments", "stage-plan"))).toBe(false);
  });
});

describe("skillsCheck", () => {
  test("reports current right after a compile", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("t");

    await skillsCompile([
      "--team", "t",
      "--pack-dir", packDir,
      "--mattstack-dir", mattstackDir,
      "--manifest", manifestPath,
      "--verb", "watch-ci",
    ]);
    logs = [];

    await skillsCheck([
      "--team", "t",
      "--pack-dir", packDir,
      "--mattstack-dir", mattstackDir,
      "--manifest", manifestPath,
      "--verb", "watch-ci",
    ]);

    expect(logs.some((l) => l.includes("watch-ci") && l.includes("current"))).toBe(true);
    expect(logs.some((l) => l.includes("stale"))).toBe(false);
    expect(process.exitCode).not.toBe(1);
  });

  test("a pipeline whose chain no longer folds is reported and exits 1", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    // Nothing before it produces "commits", and the seed does not carry it.
    writeFile(
      join(mattstackDir, "plugins", "mattstack", "attachments", "pipeline", "stage-ship", "SKILL.md"),
      `---\nname: stage-ship\ndescription: "ship stage"\ntype: pipeline-step\nmetadata:\n  stage: ship\n  stage-consumes: commits\n---\n\nship.\n`,
    );
    const manifestDir = realpathSync(mkdtempSync(join(tmpdir(), "rt-skills-cli-manifest-chain-")));
    const manifestPath = join(manifestDir, "skills.jsonc");
    writeFile(manifestPath, `{\n  "pipelines": { "feature": ["mattstack:stage-ship"] },\n  "bindings": {}\n}\n`);

    await skillsCheck([
      "--team", "t",
      "--pack-dir", packDir,
      "--mattstack-dir", mattstackDir,
      "--manifest", manifestPath,
    ]);

    expect(logs.some((l) => l.includes('stage "stage-ship" consumes "commits"'))).toBe(true);
    expect(process.exitCode).toBe(1);
  });

  test("hand-edited SKILL.md reports stale and exits 1", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("t");

    await skillsCompile([
      "--team", "t",
      "--pack-dir", packDir,
      "--mattstack-dir", mattstackDir,
      "--manifest", manifestPath,
      "--verb", "watch-ci",
    ]);

    const skillMdPath = join(packDir, "skills", "watch-ci", "SKILL.md");
    writeFileSync(skillMdPath, readFileSync(skillMdPath, "utf8") + "\nhand-edited drift\n");
    logs = [];

    await skillsCheck([
      "--team", "t",
      "--pack-dir", packDir,
      "--mattstack-dir", mattstackDir,
      "--manifest", manifestPath,
      "--verb", "watch-ci",
    ]);

    const staleLine = logs.find((l) => l.includes("stale"));
    expect(staleLine).toBeDefined();
    expect(staleLine).toContain("watch-ci");
    expect(staleLine).toContain("SKILL.md");
    expect(process.exitCode).toBe(1);
  });

  test("orphan file left over from a previous compile reports stale and exits 1", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("t");

    await skillsCompile([
      "--team", "t",
      "--pack-dir", packDir,
      "--mattstack-dir", mattstackDir,
      "--manifest", manifestPath,
      "--verb", "watch-ci",
    ]);

    writeFileSync(join(packDir, "skills", "watch-ci", "leftover.txt"), "stale content\n");
    logs = [];

    await skillsCheck([
      "--team", "t",
      "--pack-dir", packDir,
      "--mattstack-dir", mattstackDir,
      "--manifest", manifestPath,
      "--verb", "watch-ci",
    ]);

    const staleLine = logs.find((l) => l.includes("stale"));
    expect(staleLine).toBeDefined();
    expect(staleLine).toContain("watch-ci");
    expect(staleLine).toContain("leftover.txt");
    expect(process.exitCode).toBe(1);
  });

  test("a gitignored file inside the compiled dir (a __pycache__ from running its scripts) is not an orphan", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("t");
    execFileSync("git", ["init", "-q"], { cwd: packDir });
    writeFileSync(join(packDir, ".gitignore"), "__pycache__/\n");

    await skillsCompile([
      "--team", "t",
      "--pack-dir", packDir,
      "--mattstack-dir", mattstackDir,
      "--manifest", manifestPath,
      "--verb", "watch-ci",
    ]);

    mkdirSync(join(packDir, "skills", "watch-ci", "scripts", "__pycache__"), { recursive: true });
    writeFileSync(join(packDir, "skills", "watch-ci", "scripts", "__pycache__", "ci_watch.cpython-314.pyc"), "bytecode\n");
    logs = [];

    await skillsCheck([
      "--team", "t",
      "--pack-dir", packDir,
      "--mattstack-dir", mattstackDir,
      "--manifest", manifestPath,
      "--verb", "watch-ci",
    ]);

    expect(logs).toContain("watch-ci: current");
    expect(process.exitCode).not.toBe(1);
  });

  test("never-compiled public verb (missing outDir) reports stale and exits 1", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("t");

    await skillsCheck([
      "--team", "t",
      "--pack-dir", packDir,
      "--mattstack-dir", mattstackDir,
      "--manifest", manifestPath,
      "--verb", "watch-ci",
    ]);

    const staleLine = logs.find((l) => l.includes("stale"));
    expect(staleLine).toBeDefined();
    expect(staleLine).toContain("watch-ci");
    expect(process.exitCode).toBe(1);
  });

  test("provenance-only drift (marker versions, compiled recompute) is masked out: in-sync", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("t");

    await skillsCompile([
      "--team", "t",
      "--pack-dir", packDir,
      "--mattstack-dir", mattstackDir,
      "--manifest", manifestPath,
      "--verb", "watch-ci",
    ]);

    const skillMdPath = join(packDir, "skills", "watch-ci", "SKILL.md");
    const bumped = readFileSync(skillMdPath, "utf8")
      .replace(/version=\S+/g, "version=9.9.9")
      .replace(/(compiled: )"[^"]*"/, '$1"bumped"');
    writeFileSync(skillMdPath, bumped);
    logs = [];

    await skillsCheck([
      "--team", "t",
      "--pack-dir", packDir,
      "--mattstack-dir", mattstackDir,
      "--manifest", manifestPath,
      "--verb", "watch-ci",
      "--json",
    ]);

    const parsed = JSON.parse(logs.join("\n"));
    expect(parsed.verbs).toEqual([
      { name: "watch-ci", status: "in-sync", staleFiles: [], orphanFiles: [], side: "skills" },
    ]);
    expect(process.exitCode).not.toBe(1);
  });

  test("provenance-masked drift plus a real prose change still reports stale and exits 1", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("t");

    await skillsCompile([
      "--team", "t",
      "--pack-dir", packDir,
      "--mattstack-dir", mattstackDir,
      "--manifest", manifestPath,
      "--verb", "watch-ci",
    ]);

    const skillMdPath = join(packDir, "skills", "watch-ci", "SKILL.md");
    const bumped = readFileSync(skillMdPath, "utf8")
      .replace(/version=\S+/g, "version=9.9.9")
      .replace(/(compiled: )"[^"]*"/, '$1"bumped"')
      .replace("Poll the pipeline every 30s", "Poll the pipeline every 45s");
    writeFileSync(skillMdPath, bumped);
    logs = [];

    await skillsCheck([
      "--team", "t",
      "--pack-dir", packDir,
      "--mattstack-dir", mattstackDir,
      "--manifest", manifestPath,
      "--verb", "watch-ci",
    ]);

    const staleLine = logs.find((l) => l.includes("stale"));
    expect(staleLine).toBeDefined();
    expect(staleLine).toContain("watch-ci");
    expect(staleLine).toContain("SKILL.md");
    expect(process.exitCode).toBe(1);
  });
});

describe("skillsCheck --json", () => {
  test("emits one row per verb (never compiled)", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("acme");

    await skillsCheck(["--pack", "acme", "--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--json"]);

    const parsed = JSON.parse(logs.join("\n"));
    expect(parsed.pack).toBe("acme");
    expect(parsed.packDir).toBe(packDir);
    expect(parsed.verbs).toEqual([
      { name: "watch-ci", status: "never-compiled", staleFiles: [], orphanFiles: [], side: "skills" },
    ]);
    expect(parsed.chainErrors).toEqual([]);
  });

  test("a broken chain rides the payload, not just the exit code", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    writeFile(
      join(mattstackDir, "plugins", "mattstack", "attachments", "pipeline", "stage-ship", "SKILL.md"),
      `---\nname: stage-ship\ndescription: "ship stage"\ntype: pipeline-step\nmetadata:\n  stage: ship\n  stage-consumes: commits\n---\n\nship.\n`,
    );
    const manifestDir = realpathSync(mkdtempSync(join(tmpdir(), "rt-skills-cli-manifest-chain-json-")));
    const manifestPath = join(manifestDir, "skills.jsonc");
    writeFile(manifestPath, `{\n  "pipelines": { "feature": ["mattstack:stage-ship"] },\n  "bindings": {}\n}\n`);

    await skillsCheck([
      "--team", "t",
      "--pack-dir", packDir,
      "--mattstack-dir", mattstackDir,
      "--manifest", manifestPath,
      "--json",
    ]);

    const parsed = JSON.parse(logs.join("\n"));
    expect(parsed.chainErrors).toHaveLength(1);
    expect(parsed.chainErrors[0]).toContain('stage "stage-ship" consumes "commits"');
    // Rows are untouched by a pack-level failure -- the console reads them.
    expect(parsed.verbs.every((v: { status: string }) => typeof v.status === "string")).toBe(true);
    expect(process.exitCode).toBe(1);
  });

  test("prints ONLY json -- no human lines on stdout", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("acme");

    await skillsCheck(["--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--json"]);

    expect(() => JSON.parse(logs.join("\n"))).not.toThrow();
  });

  test("reports in-sync right after a compile", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("acme");

    await skillsCompile(["--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--verb", "watch-ci"]);
    logs = [];

    await skillsCheck(["--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--json"]);

    const parsed = JSON.parse(logs.join("\n"));
    expect(parsed.verbs).toEqual([
      { name: "watch-ci", status: "in-sync", staleFiles: [], orphanFiles: [], side: "skills" },
    ]);
    expect("staleBecause" in parsed.verbs[0]).toBe(false);
  });

  test("separates staleFiles (content drift) from orphanFiles (leftover) instead of merging them", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("acme");

    await skillsCompile(["--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--verb", "watch-ci"]);
    const skillMdPath = join(packDir, "skills", "watch-ci", "SKILL.md");
    writeFileSync(skillMdPath, readFileSync(skillMdPath, "utf8") + "\nhand-edited drift\n");
    writeFileSync(join(packDir, "skills", "watch-ci", "leftover.txt"), "stale content\n");
    logs = [];

    await skillsCheck(["--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--json"]);

    const parsed = JSON.parse(logs.join("\n"));
    expect(parsed.verbs).toEqual([
      { name: "watch-ci", status: "stale", staleFiles: ["SKILL.md"], orphanFiles: ["leftover.txt"], side: "skills", staleBecause: ["fill"] },
    ]);
    expect(process.exitCode).toBe(1);
  });

  test("engine body edited: staleBecause names the source", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("acme");

    await skillsCompile(["--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--verb", "watch-ci"]);

    writeFile(
      join(mattstackDir, "plugins", "mattstack", "skills", "pipeline", "watch-ci", "SKILL.md"),
      WATCH_CI_SKILL_MD.replace("Poll the pipeline every 30s", "Poll the pipeline every 60s"),
    );
    logs = [];

    await skillsCheck(["--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--json"]);

    const verb = JSON.parse(logs.join("\n")).verbs[0];
    expect(verb.status).toBe("stale");
    expect(verb.staleFiles).toEqual(["SKILL.md"]);
    expect(verb.staleBecause).toEqual(["source"]);
  });

  test("fill body edited: staleBecause names the fill", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("acme");

    await skillsCompile(["--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--verb", "watch-ci"]);

    writeFile(
      join(mattstackDir, "plugins", "acme", "attachments", "watch-ci-domain", "SKILL.md"),
      DOMAIN_SKILL_MD.replace("Domain rules live at", "Domain rules now live at"),
    );
    logs = [];

    await skillsCheck(["--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--json"]);

    const verb = JSON.parse(logs.join("\n")).verbs[0];
    expect(verb.status).toBe("stale");
    expect(verb.staleBecause).toEqual(["fill"]);
  });

  test("roster description edited: staleBecause names frontmatter", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("acme");

    await skillsCompile(["--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--verb", "watch-ci"]);

    writeFile(
      join(packDir, "pack", "stubs.jsonc"),
      STUBS_JSONC.replace("Use when watching or triaging CI.", "Use when watching CI."),
    );
    logs = [];

    await skillsCheck(["--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--json"]);

    const verb = JSON.parse(logs.join("\n")).verbs[0];
    expect(verb.status).toBe("stale");
    expect(verb.staleBecause).toEqual(["frontmatter"]);
  });

  test("vendored script edited: staleBecause names vendored", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("acme");

    await skillsCompile(["--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--verb", "watch-ci"]);

    writeFile(
      join(mattstackDir, "plugins", "mattstack", "skills", "pipeline", "watch-ci", "scripts", "ci-watch.sh"),
      "#!/bin/sh\necho polling twice\n",
    );
    logs = [];

    await skillsCheck(["--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--json"]);

    const verb = JSON.parse(logs.join("\n")).verbs[0];
    expect(verb.status).toBe("stale");
    expect(verb.staleFiles).toEqual(["scripts/ci-watch.sh"]);
    expect(verb.staleBecause).toEqual(["vendored"]);
  });

  test("internal verb with missing outDir: never-compiled under attachments/, and still counts as stale", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("acme");
    writeFile(join(packDir, "pack", "surface.jsonc"), `{ "public": [] }\n`);

    await skillsCheck(["--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--json"]);

    const parsed = JSON.parse(logs.join("\n"));
    expect(parsed.verbs).toEqual([
      { name: "watch-ci", status: "never-compiled", staleFiles: [], orphanFiles: [], side: "attachments" },
    ]);
    expect(process.exitCode).toBe(1);
  });
});

describe("skillsCompile --json", () => {
  test("compiled verb: files + warnings reported, files written to disk like the plain form", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("acme");

    await skillsCompile(["--pack", "acme", "--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--verb", "watch-ci", "--json"]);

    const parsed = JSON.parse(logs.join("\n"));
    expect(parsed.pack).toBe("acme");
    expect(parsed.written).toBe(true);
    expect(parsed.verbs).toHaveLength(1);
    const verb = parsed.verbs[0];
    expect(verb.name).toBe("watch-ci");
    expect(verb.status).toBe("compiled");
    expect(verb.errors).toEqual([]);
    expect(verb.files.map((f: { path: string }) => f.path).sort()).toEqual([
      "SKILL.md",
      "parts/domain/ci-config.json",
      "scripts/ci-watch.sh",
    ]);
    for (const file of verb.files) {
      expect(existsSync(join(packDir, "skills", "watch-ci", file.path))).toBe(true);
    }
    // A clean compile leaves the exit code unset: a caller reading it sees success.
    expect(process.exitCode).not.toBe(1);
  });

  test("internal (retired) verb: compiled row with side attachments, written to the attachments side", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("acme");
    writeFile(join(packDir, "pack", "surface.jsonc"), `{ "public": [] }\n`);

    await skillsCompile(["--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--verb", "watch-ci", "--json"]);

    const parsed = JSON.parse(logs.join("\n"));
    expect(parsed.verbs).toHaveLength(1);
    const verb = parsed.verbs[0];
    expect(verb.name).toBe("watch-ci");
    expect(verb.status).toBe("compiled");
    expect(verb.side).toBe("attachments");
    expect(verb.errors).toEqual([]);
    expect(verb.files.map((f: { path: string }) => f.path).sort()).toEqual([
      "SKILL.md",
      "parts/domain/ci-config.json",
      "scripts/ci-watch.sh",
    ]);
    expect(existsSync(join(packDir, "attachments", "watch-ci", "SKILL.md"))).toBe(true);
    expect(existsSync(join(packDir, "skills", "watch-ci"))).toBe(false);
  });

  test("lint-erroring verb (returned errors[]): errored with the message, other verbs unaffected -- command does not die", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    writeFile(join(packDir, "pack", "stubs.jsonc"), STUBS_WITH_INTERNAL_REF);
    writeFile(join(packDir, "pack", "surface.jsonc"), `{ "public": ["watch-ci"] }\n`);
    const manifestPath = makeManifest("acme");

    await skillsCompile(["--pack", "acme", "--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--json"]);

    const parsed = JSON.parse(logs.join("\n"));
    const watchCi = parsed.verbs.find((v: { name: string }) => v.name === "watch-ci");
    expect(watchCi.status).toBe("errored");
    expect(watchCi.files).toEqual([]);
    expect(watchCi.errors).toHaveLength(1);
    expect(watchCi.errors[0]).toContain("acme:helper-verb");

    const helper = parsed.verbs.find((v: { name: string }) => v.name === "helper-verb");
    expect(helper.status).toBe("compiled");
    expect(helper.side).toBe("attachments");

    // An errored verb is a failed compile: the exit code says so, matching the
    // non-JSON throw and check --json's stale exit.
    expect(process.exitCode).toBe(1);
  });

  test("unbound required slot (compileVerb throws): errored, not a crash", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("acme", false);

    await skillsCompile(["--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--verb", "watch-ci", "--json"]);

    const parsed = JSON.parse(logs.join("\n"));
    expect(parsed.verbs).toHaveLength(1);
    expect(parsed.verbs[0].status).toBe("errored");
    expect(parsed.verbs[0].files).toEqual([]);
    expect(parsed.verbs[0].errors[0]).toContain("forge");
    expect(process.exitCode).toBe(1);
  });

  test("prints ONLY json -- no human lines on stdout", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("acme");

    await skillsCompile(["--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--verb", "watch-ci", "--json"]);

    expect(() => JSON.parse(logs.join("\n"))).not.toThrow();
  });
});

describe("skillsCompile --preview error handling", () => {
  test("lint-erroring verb: message on stderr, empty stdout, exit code set but no crash", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    writeFile(join(packDir, "pack", "stubs.jsonc"), STUBS_WITH_INTERNAL_REF);
    writeFile(join(packDir, "pack", "surface.jsonc"), `{ "public": ["watch-ci"] }\n`);
    const manifestPath = makeManifest("acme");

    const errors: string[] = [];
    const errorSpy = spyOn(console, "error").mockImplementation((...args: unknown[]) => {
      errors.push(args.map(String).join(" "));
    });
    try {
      await skillsCompile([
        "--pack", "acme", "--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath,
        "--verb", "watch-ci", "--preview",
      ]);
    } finally {
      errorSpy.mockRestore();
    }

    expect(logs).toEqual([]);
    expect(errors.join("\n")).toContain("acme:helper-verb");
    expect(process.exitCode).toBe(1);
  });

  test("erroring verb in a pack that ALSO has a misplaced compiled dir: still nothing on stdout", async () => {
    // Before the per-verb try/catch, an error always exited the whole command
    // immediately, so the post-loop "misplaced" scan (which prints to stdout)
    // was unreachable on any --preview error path. A bare `continue` in the
    // catch would let the loop end normally (--preview is single-verb) and
    // fall straight into that scan -- leaking a "misplaced: ..." line onto
    // stdout, breaking --preview's stdout-is-the-body-or-nothing contract.
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    writeFile(join(packDir, "pack", "stubs.jsonc"), STUBS_WITH_INTERNAL_REF);
    writeFile(join(packDir, "pack", "surface.jsonc"), `{ "public": ["watch-ci"] }\n`);
    writeFile(join(packDir, "skills", "leftover-verb", "SKILL.md"), "---\nname: leftover-verb\n---\nstale\n");
    const manifestPath = makeManifest("acme");

    const errors: string[] = [];
    const errorSpy = spyOn(console, "error").mockImplementation((...args: unknown[]) => {
      errors.push(args.map(String).join(" "));
    });
    try {
      await skillsCompile([
        "--pack", "acme", "--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath,
        "--verb", "watch-ci", "--preview",
      ]);
    } finally {
      errorSpy.mockRestore();
    }

    expect(logs).toEqual([]);
    expect(errors.join("\n")).toContain("acme:helper-verb");
  });

  test("unbound required slot: message on stderr, empty stdout, exit code set but no crash", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("acme", false);

    const errors: string[] = [];
    const errorSpy = spyOn(console, "error").mockImplementation((...args: unknown[]) => {
      errors.push(args.map(String).join(" "));
    });
    try {
      await skillsCompile([
        "--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath,
        "--verb", "watch-ci", "--preview",
      ]);
    } finally {
      errorSpy.mockRestore();
    }

    expect(logs).toEqual([]);
    expect(errors.join("\n")).toContain("forge");
    expect(process.exitCode).toBe(1);
  });
});

describe("skillsComposition --json", () => {
  test("verb, slots, fills, and binders reflect the manifest", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("acme");

    await skillsComposition(["--pack", "acme", "--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--json"]);

    const parsed = JSON.parse(logs.join("\n"));
    expect(parsed.pack).toBe("acme");
    expect(parsed.packDir).toBe(packDir);
    expect(parsed.verbs).toHaveLength(1);

    const verb = parsed.verbs[0];
    expect(verb.name).toBe("watch-ci");
    expect(verb.engine).toBe("watch-ci");
    expect(verb.engineRef).toBe("mattstack:watch-ci");
    expect(verb.plugin).toBe("mattstack");
    expect(verb.public).toBe(true);
    expect(verb.sourcePath).toBe(join(mattstackDir, "plugins", "mattstack", "skills", "pipeline", "watch-ci", "SKILL.md"));
    expect(verb.artifactPath).toBe(join(packDir, "skills", "watch-ci"));
    expect(verb.engineError).toBeUndefined();
    expect(verb.includes).toEqual([]);

    const domainSlot = verb.slots.find((s: { name: string }) => s.name === "domain");
    expect(domainSlot.contract).toBe("watch-ci-domain@1");
    expect(domainSlot.required).toBe(false);
    expect(domainSlot.boundTo).toBe("acme:watch-ci-domain");
    expect(domainSlot.fillSourcePath).toBe(
      join(mattstackDir, "plugins", "acme", "attachments", "watch-ci-domain", "SKILL.md"),
    );
    expect(domainSlot.fillVersion).toBe("0.3.0");
    expect(domainSlot.registered).toBe(false);
    expect(domainSlot.inlined).toBe(true);
    expect(domainSlot.resolveError).toBeUndefined();

    const forgeSlot = verb.slots.find((s: { name: string }) => s.name === "forge");
    expect(forgeSlot.required).toBe(true);
    expect(forgeSlot.boundTo).toBe("mattstack:gitlab-forge");
    expect(forgeSlot.registered).toBe(true);
    expect(forgeSlot.inlined).toBe(false);

    expect(parsed.fills).toHaveLength(2);
    const domainFill = parsed.fills.find((f: { binding: string }) => f.binding === "acme:watch-ci-domain");
    expect(domainFill).toEqual({
      binding: "acme:watch-ci-domain",
      provides: "watch-ci-domain@1",
      sourcePath: join(mattstackDir, "plugins", "acme", "attachments", "watch-ci-domain", "SKILL.md"),
      registered: false,
    });
    const forgeFill = parsed.fills.find((f: { binding: string }) => f.binding === "mattstack:gitlab-forge");
    expect(forgeFill.registered).toBe(true);
    expect(forgeFill.provides).toBe("ci-forge@1");

    const binder = parsed.binders.find((b: { ref: string }) => b.ref === "mattstack:watch-ci");
    expect(binder.verb).toBe("watch-ci");
    expect(binder.kind).toBe("verb");
    expect(binder.slots).toEqual([
      { name: "domain", boundTo: "acme:watch-ci-domain" },
      { name: "forge", boundTo: "mattstack:gitlab-forge" },
    ]);
  });

  test("includes names every {{include}} the engine and its bound fills carry, pre-compile", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("acme");
    writeFile(
      join(mattstackDir, "plugins", "mattstack", "skills", "pipeline", "watch-ci", "SKILL.md"),
      WATCH_CI_SKILL_MD.replace(
        "Poll the pipeline every 30s and report status.",
        "{{include:ci-note}}\n\n{{slot:domain}}\n\n{{slot:forge}}\n\n{{include:ci-note}}\n\nPoll the pipeline every 30s and report status.",
      ),
    );
    writeFile(
      join(mattstackDir, "plugins", "acme", "attachments", "watch-ci-domain", "SKILL.md"),
      DOMAIN_SKILL_MD + "\n{{include:fill-note}}\n",
    );

    await skillsComposition(["--pack", "acme", "--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--json"]);

    const verb = JSON.parse(logs.join("\n")).verbs[0];
    expect(verb.includes).toEqual(["ci-note", "fill-note"]);
  });

  test("an include reached only through a reference-mode (registered, public) fill is not scanned or vendored", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("acme");
    writeFile(
      join(mattstackDir, "plugins", "mattstack", "skills", "gitlab-forge", "SKILL.md"),
      FORGE_SKILL_MD + "\n{{include:forge-note}}\n",
    );
    writeFile(
      join(mattstackDir, "plugins", "mattstack", "attachments", "forge-note", "SKILL.md"),
      "---\nname: forge-note\n---\n\nforge note body\n",
    );
    writeFile(join(mattstackDir, "plugins", "mattstack", "attachments", "forge-note", "note.txt"), "note\n");

    await skillsComposition(["--pack", "acme", "--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--json"]);
    const verb = JSON.parse(logs.join("\n")).verbs[0];
    expect(verb.includes).toEqual([]);

    logs = [];
    await skillsCompile(["--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath]);
    expect(existsSync(join(packDir, "skills", "watch-ci", "parts", "include-forge-note"))).toBe(false);
  });

  test("an internal verb's artifactPath is under attachments/, not a hardcoded skills/", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    writeFile(join(packDir, "pack", "surface.jsonc"), `{ "public": [] }\n`);
    const manifestPath = makeManifest("acme");

    await skillsComposition(["--pack", "acme", "--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--json"]);

    const parsed = JSON.parse(logs.join("\n"));
    const verb = parsed.verbs.find((v: { name: string }) => v.name === "watch-ci");
    expect(verb.public).toBe(false);
    expect(verb.artifactPath).toBe(join(packDir, "attachments", "watch-ci"));
  });

  test("degrades per-slot (dangling binding) and per-verb (broken engine) without blanking the payload", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    writeFile(join(packDir, "pack", "stubs.jsonc"), STUBS_TWO_VERBS);
    const manifestPath = makeManifestDanglingDomain();

    await skillsComposition(["--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--json"]);

    const parsed = JSON.parse(logs.join("\n"));
    expect(parsed.verbs).toHaveLength(2);

    const watchCi = parsed.verbs.find((v: { name: string }) => v.name === "watch-ci");
    expect(watchCi.engineRef).toBe("mattstack:watch-ci");
    expect(watchCi.engineError).toBeUndefined();
    const domainSlot = watchCi.slots.find((s: { name: string }) => s.name === "domain");
    expect(domainSlot.boundTo).toBe("acme:does-not-exist");
    expect(domainSlot.resolveError).toContain("does-not-exist");
    expect(domainSlot.fillSourcePath).toBeNull();
    expect(domainSlot.fillVersion).toBeNull();
    const forgeSlot = watchCi.slots.find((s: { name: string }) => s.name === "forge");
    expect(forgeSlot.resolveError).toBeUndefined();
    expect(forgeSlot.fillSourcePath).not.toBeNull();

    const broken = parsed.verbs.find((v: { name: string }) => v.name === "broken");
    expect(broken.engineRef).toBeNull();
    expect(broken.plugin).toBeNull();
    expect(broken.sourcePath).toBeNull();
    expect(broken.slots).toEqual([]);
    expect(broken.engineError).toContain("no-such-engine");
    expect(broken.artifactPath).toBe(join(packDir, "skills", "broken"));

    // The payload as a whole is still populated -- one broken verb/slot pair
    // does not blank fills or binders either.
    expect(parsed.fills.length).toBeGreaterThan(0);
    expect(parsed.binders.length).toBeGreaterThan(0);
  });

  test("ignores a stray --verb flag: verbs stays the full roster, never truncated", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    writeFile(join(packDir, "pack", "stubs.jsonc"), STUBS_TWO_VERBS);
    const manifestPath = makeManifest("acme");

    await skillsComposition([
      "--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath,
      "--verb", "watch-ci", "--json",
    ]);

    const parsed = JSON.parse(logs.join("\n"));
    expect(parsed.verbs.map((v: { name: string }) => v.name).sort()).toEqual(["broken", "watch-ci"]);
  });

  test("binder kind is derived from pipelines/roster membership, not a ref string heuristic", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestDir = realpathSync(mkdtempSync(join(tmpdir(), "rt-skills-cli-manifest-")));
    const manifestPath = join(manifestDir, "skills.jsonc");
    writeFile(manifestPath, `{
  "pipelines": {
    "feature": ["mattstack:stage-provision"]
  },
  "bindings": {
    "mattstack:watch-ci": {
      "domain": "acme:watch-ci-domain",
      "forge": "mattstack:gitlab-forge"
    },
    "mattstack:stage-provision": {
      "domain": "acme:watch-ci-domain"
    },
    "mattstack:review-core": {
      "criteria": "acme:watch-ci-domain"
    },
    "board:review": {
      "skill": "acme:watch-ci-domain"
    }
  }
}
`);

    await skillsComposition(["--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--json"]);

    const parsed = JSON.parse(logs.join("\n"));
    const byRef = Object.fromEntries(parsed.binders.map((b: { ref: string; kind: string; verb: string | null }) => [b.ref, b]));

    // mattstack:stage-provision has NO roster verb, so this also proves kind
    // isn't derived by string-matching "stage-" -- only pipelines membership does it.
    expect(byRef["mattstack:watch-ci"]).toMatchObject({ kind: "verb", verb: "watch-ci" });
    expect(byRef["mattstack:stage-provision"]).toMatchObject({ kind: "stage", verb: null });
    expect(byRef["mattstack:review-core"]).toMatchObject({ kind: "skill", verb: null });
    expect(byRef["board:review"]).toMatchObject({ kind: "external", verb: null });
  });

  test("rosterless pack: empty verbs, fills, and binders -- not a failure", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = realpathSync(mkdtempSync(join(tmpdir(), "rt-skills-cli-pack-empty-")));

    await skillsComposition(["--pack", "acme", "--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--json"]);

    const parsed = JSON.parse(logs.join("\n"));
    expect(parsed).toEqual({ pack: "acme", packDir, manifestPath: null, verbs: [], fills: [], binders: [], pipelines: {} });
  });

  test("manifestPath is the absolute manifest the bindings came from, not <packDir>/skills.jsonc", async () => {
    // The console names this path as the file to edit to rebind a slot. It is
    // NOT reconstructable from the pack name -- it lives in a registered repo
    // dir -- so the payload has to carry the real one or the console guesses.
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestDir = realpathSync(mkdtempSync(join(tmpdir(), "rt-skills-cli-manifest-path-")));
    const manifestPath = join(manifestDir, "skills.jsonc");
    writeFile(manifestPath, `{ "bindings": { "mattstack:watch-ci": { "domain": "acme:watch-ci-domain" } } }`);

    await skillsComposition(["--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--json"]);

    const parsed = JSON.parse(logs.join("\n"));
    expect(parsed.manifestPath).toBe(manifestPath);
    expect(parsed.manifestPath).not.toBe(join(packDir, "skills.jsonc"));
  });

  test("pipelines carries each work type's stage order, not a set", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestDir = realpathSync(mkdtempSync(join(tmpdir(), "rt-skills-cli-manifest-order-")));
    const manifestPath = join(manifestDir, "skills.jsonc");
    // Deliberately NOT alphabetical: ship precedes provision. Anything that
    // rebuilt this list from binders[] or routed it through a Set would come
    // back sorted or in binding-insertion order, and a consumer rendering
    // execution order would show the pipeline running backwards with nothing
    // failing anywhere.
    writeFile(manifestPath, `{
  "pipelines": {
    "feature": ["mattstack:stage-ship", "mattstack:stage-provision", "mattstack:stage-plan"],
    "bugfix": ["mattstack:stage-provision"]
  },
  "bindings": {
    "mattstack:watch-ci": {
      "domain": "acme:watch-ci-domain"
    }
  }
}
`);

    await skillsComposition(["--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--json"]);

    const parsed = JSON.parse(logs.join("\n"));
    expect(parsed.pipelines).toEqual({
      feature: ["mattstack:stage-ship", "mattstack:stage-provision", "mattstack:stage-plan"],
      bugfix: ["mattstack:stage-provision"],
    });
  });

  test("prints ONLY json -- no human lines on stdout", async () => {
    const mattstackDir = makeMattstackDir();
    const packDir = makePackDir();
    const manifestPath = makeManifest("acme");

    await skillsComposition(["--pack-dir", packDir, "--mattstack-dir", mattstackDir, "--manifest", manifestPath, "--json"]);

    expect(() => JSON.parse(logs.join("\n"))).not.toThrow();
  });
});

describe("skillsPacks --json", () => {
  test("no packs discovered: empty packs array, not an error", async () => {
    await skillsPacks(["--settings-path", "/nonexistent/settings.json", "--json"]);

    const parsed = JSON.parse(logs.join("\n"));
    expect(parsed).toEqual({ packs: [] });
  });

  test("prints ONLY json -- no human lines on stdout", async () => {
    await skillsPacks(["--settings-path", "/nonexistent/settings.json", "--json"]);

    expect(() => JSON.parse(logs.join("\n"))).not.toThrow();
  });
});
